/*****************************************************************************
 * Copyright (c) 2014-2026 OpenRCT2 developers
 *
 * For a complete list of all authors, please refer to contributors.md
 * Interested in contributing? Visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is licensed under the GNU General Public License version 3.
 *****************************************************************************/

#include "Rct1TrackDesignNames.h"

#include <utility>

namespace OpenRCT2::RCT1
{
    // clang-format off
    static constexpr std::pair<std::string_view, std::string_view> kDeluxeTrackDesignNames[] = {
        { "u(0010)",  "Apollo" },
        { "u(0016)",  "Storm Squad" },
        { "u(0018)",  "Eruption" },
        { "u(0050)",  "Twistycart" },
        { "u(0058)",  "Bad Bat" },
        { "u(0059)",  "Blue Angels" },
        { "u(0061)",  "Coming and Going" },
        { "u(0062)",  "Corkscrewy" },
        { "u(0064)",  "Double Deluge" },
        { "u(0065)",  "Double Dipper" },
        { "u(0070)",  "Double Dynamite" },
        { "u(0072)",  "Double Header" },
        { "u(0073)",  "Double Helix" },
        { "u(0074)",  "Double Indemnity" },
        { "u(0075)",  "Double Jeopardy" },
        { "u(0076)",  "Double or Nothing" },
        { "u(0078)",  "Double Scoop Cone" },
        { "u(0080)",  "Double Trouble" },
        { "u(0081)",  "Double Vision" },
        { "u(0082)",  "Double Whammy" },
        { "u(0085)",  "Duelling Lumberjacks" },
        { "u(0087)",  "Flamingo Road" },
        { "u(0089)",  "Flynamic Duo" },
        { "u(0092)",  "Hyper Viper" },
        { "u(0093)",  "Indianapolis 5,000" },
        { "u(0094)",  "Invertigo" },
        { "u(0096)",  "Ketchup vs Mustard" },
        { "u(0105)",  "Oliver Twisters" },
        { "u(0106)",  "Over the Top" },
        { "u(0111)",  "Reel to Reel" },
        { "u(0114)",  "Skinny Winnie" },
        { "u(0117)",  "Spaghetti Looper" },
        { "u(0119)",  "Stand Up and Cheer!" },
        { "u(0120)",  "Super Duper Sonic" },
        { "u(0125)",  "Turbulence" },
        { "u(0126)",  "Twin Cities Cyclones" },
        { "u(0128)",  "Vertical Limit" },
        { "u(0129)",  "Vertiginous" },
        { "u(0137)",  "Kong" },
        { "u(0143)",  "Brick Racing Unit" },
        { "u(0144)",  "Little Shrimpy" },
        { "u(0150)",  "The In Version" },
        { "u(0156)",  "Mega Race" },
        { "u(0157)",  "Super Mega Race" },
        { "u(0166)",  "D-Devil" },
        { "u(0224)",  "Big Art" },
        { "u(0236)",  "Vertical Horizon" },
        { "u(0237)",  "Kamikaze" },
        { "u(0241)",  "Barbeque" },
        { "u(0248)",  "Earthquake" },
        { "u(0249)",  "Air" },
        { "u(0251)",  "Neon Rush" },
        { "u(0258)",  "The Wildcat" },
        { "u(0275)",  "Super Flume" },
        { "u(0278)",  "Mercenary" },
        { "u(0340)",  "Cobra" },
        { "u(0380)",  "Terminator" },
        { "u(0381)",  "Twisted Twins Two" },
        { "u(0400)",  "On the Green Cheese" },
        { "u(0401)",  "Yellow Devil" },
        { "u(0413)",  "Predator" },
        { "u(0425)",  "Cool Spinner" },
        { "u(0473)",  "Black Illusion" },
        { "u(0474)",  "Anarchy" },
        { "u(0486)",  "Ultimate Coaster" },
        { "u(0489)",  "Hung Mice" },
        { "u(0508)",  "Wicked Twister" },
        { "u(0561)",  "Black Thunder" },
        { "u(0608)",  "Water Splashing" },
        { "u(0610)",  "Plain White Coaster" },
        { "u(0633)",  "Mini Bobsled Coaster" },
        { "u(0643)",  "Quiver" },
        { "u(0677)",  "X" },
        { "u(0682)",  "The Black Dragon" },
        { "u(0706)",  "Zero Gravity" },
        { "u(0709)",  "Super Freefall Crowd Builder" },
        { "u(0725)",  "Liquid Steel III" },
        { "u(0726)",  "Loopy Tunes" },
        { "u(0727)",  "The Matrix" },
        { "u(0732)",  "Compact" },
        { "u(0738)",  "The Jackal" },
        { "u(0753)",  "Grave Digger" },
        { "u(0777)",  "Robin Hood" },
        { "u(0778)",  "Whirling Comet" },
        { "u(0832)",  "Periwinkle Parkway" },
        { "u(0844)",  "Desert Penguin's Revenge" },
        { "u(0849)",  "Big Red Steel" },
        { "u(0931)",  "Friction Frenzy" },
        { "u(0957)",  "The Wild Bear" },
        { "u(0968)",  "Gold Rush" },
        { "u(0974)",  "Bumpy Boats" },
        { "u(0975)",  "Need For Speed II" },
        { "u(0989)",  "Generation X" },
        { "u(0995)",  "The Joust" },
        { "u(1005)",  "Double Death Spins" },
        { "u(1008)",  "Go Karts Competition" },
        { "u(1012)",  "Lucky 13 With a Loop" },
        { "u(1061)",  "Yoda" },
        { "u(1109)",  "Cool Runnings" },
        { "u(1114)",  "White Hot II" },
        { "u(1167)",  "Zoom Loop" },
        { "u(1235)",  "Fits All Parks" },
        { "u(1236)",  "Talon" },
        { "u(1301)",  "Alien 2" },
        { "u(1302)",  "Alien Invasion" },
        { "u(1333)",  "Chameleon" },
        { "u(1398)",  "Cyclone II" },
        { "u(1412)",  "Spider-Man - The Coaster" },
        { "u(1418)",  "Com-Bat" },
        { "u(1447)",  "Perfect!" },
        { "u(1454)",  "Cliff Hanger" },
        { "u(1514)",  "Mini Cyclone" },
        { "u(1526)",  "Cool Bob" },
        { "u(1645)",  "Small Bobsled Coaster" },
        { "u(1668)",  "Flying Squirrel" },
        { "u(1676)",  "Ultima" },
        { "u(1735)",  "Super Duper Mega Circuit" },
        { "u(1736)",  "Transis Grapevine" },
        { "u(1737)",  "Nascar Thunder 2002" },
        { "u(1738)",  "Daytona 2002" },
        { "u(1752)",  "Driving School" },
        { "u(1760)",  "Alien Experience" },
        { "u(1797)",  "Bee-Line" },
        { "u(1798)",  "8 Blind Mice" },
        { "u(1800)",  "Bugged Out" },
        { "u(1801)",  "Cool Island Breeze" },
        { "u(1807)",  "Haunted Screamer" },
        { "u(1819)",  "Lazy Lumberjack's Jump" },
        { "u(1825)",  "Raiders" },
        { "u(1836)",  "Turbulence" },
        { "u(1844)",  "0 Degreez" },
        { "u(1863)",  "Rainforest Canopy" },
        { "u(1869)",  "Fissure" },
        { "u(1870)",  "Ben VI" },
        { "u(1872)",  "Rainbow Connection" },
        { "u(1873)",  "The Reason III" },
        { "u(1887)",  "Always Tilted" },
        { "u(1894)",  "Bigger Death Loops" },
        { "u(2004)",  "Alpine Skier" },
        { "u(2081)",  "Halloween H2O" },
        { "u(2085)",  "Hill Karts" },
        { "u(2086)",  "Lap Counter" },
        { "u(2109)",  "Gravity Booster" },
        { "u(2132)",  "Blade" },
        { "u(2146)",  "Mind Power" },
        { "u(2169)",  "Iron Maiden" },
        { "u(2194)",  "Cobra Strike" },
        { "u(2210)",  "Red Rocket" },
        { "u(2235)",  "Cold Fusion" },
        { "u(2273)",  "Air Time" },
        { "u(2275)",  "Insecto" },
        { "u(2281)",  "Acconeer" },
        { "u(2294)",  "Greater Racers" },
        { "u(2315)",  "Death Road" },
        { "u(2373)",  "Log Flume Race" },
        { "u(2400)",  "Bolt From the Blue" },
        { "u(2402)",  "Wet-n-Wild" },
        { "u(2406)",  "Thundering Rishav" },
        { "u(2446)",  "Blastonator" },
        { "u(2448)",  "Beto Carrero" },
        { "u(2466)",  "Tangled Yarn" },
        { "u(2479)",  "P" },
        { "u(2480)",  "Anaconda 6.0" },
        { "u(2487)",  "Doom Flier" },
        { "u(2526)",  "Triple Decker Karts" },
        { "u(2530)",  "America's Coaster" },
        { "u(2532)",  "Get Vertical" },
        { "u(2543)",  "Mega Freefall" },
        { "u(2545)",  "Mini Train Ride" },
        { "u(2717)",  "Memorex" },
        { "u(2750)",  "Face-Off" },
        { "u(2794)",  "Black Scorpion" },
        { "u(2809)",  "Big Bomb" },
        { "u(2818)",  "All Corkscrew" },
        { "u(2834)",  "Child Cry" },
        { "u(2883)",  "Concrete Jungle" },
        { "u(2889)",  "Ancient Power" },
        { "u(2918)",  "Binoculars" },
        { "u(2983)",  "Double Fissure" },
        { "u(3010)",  "Hyperjet 2001" },
        { "u(3039)",  "Stop, Drop, and Roll" },
        { "u(3052)",  "Buster Slash" },
        { "u(3060)",  "It's All About Profit" },
        { "u(3123)",  "Come On, Have Fun!" },
        { "u(3179)",  "3-Floor Karts" },
        { "u(3203)",  "XXI" },
        { "u(3323)",  "Shuttle Loop 3" },
        { "u(3332)",  "Through the Loops" },
        { "u(3345)",  "Arid Blazer" },
        { "u(3347)",  "Beach Rumbler" },
        { "u(3385)",  "Alpine Mountain" },
        { "u(3411)",  "Car Twister II" },
        { "u(3413)",  "Crankshaft" },
        { "u(3430)",  "Glitcher" },
        { "u(3614)",  "3 Corkscrews" },
        { "u(3628)",  "La Montana Rusa" },
        { "u(3648)",  "Lasso Trunk" },
        { "u(3772)",  "Black Balthazar" },
        { "u(3809)",  "Inverse" },
        { "u(3941)",  "Mega Bob" },
        { "u(3985)",  "Batman (New Maker)" },
        { "u(3995)",  "Angel Falls" },
        { "u(4068)",  "Apocalypse" },
        { "u(4078)",  "3 - O" },
        { "u(4122)",  "Claustrophobia" },
        { "u(4138)",  "Bobman" },
        { "u(4281)",  "Black Hole Water Slide" },
        { "u(4286)",  "Flame Shuttle" },
        { "u(4326)",  "Extreme Rider" },
        { "u(4407)",  "Big-Little Monster" },
        { "u(4447)",  "Big 80" },
        { "u(4448)",  "Coil's Revenge Part 1" },
        { "u(4460)",  "The Wet Flush" },
        { "u(4463)",  "The Blue Angel" },
        { "u(4491)",  "Around and About" },
        { "u(4499)",  "Force 4" },
        { "u(4531)",  "Cherry Bomb" },
        { "u(4538)",  "Beast" },
        { "u(4549)",  "Boa Constrictor 2" },
        { "u(4559)",  "Incredible 4-Story Go-Karts" },
        { "u(4560)",  "Hazardous Materials" },
        { "u(4725)",  "Abstract Mini-Golf" },
        { "u(4764)",  "Shuttle Loop Xtreme" },
        { "u(4955)",  "Bloody Horror" },
        { "u(5299)",  "Big Mine Truck Island" },
        { "u(5432)",  "Blood Drop" },
        { "u(5501)",  "Blast-Off to Nowhere" },
        { "u(5639)",  "Jungle Explorer" },
        { "u(5647)",  "Lord of the Rings" },
        { "u(5827)",  "Blue Horror" },
        { "u(5830)",  "Bass-Ackwards" },
        { "u(5895)",  "Zorg Tower" },
        { "u(5897)",  "Die Hard" },
        { "u(5899)",  "Die Hard With a Vengeance" },
        { "u(5924)",  "1st Blood" },
        { "u(5928)",  "Splinter Cell" },
        { "u(6076)",  "Bugsy" },
        { "u(6127)",  "Crazy Inverted Mouse" },
        { "u(6645)",  "A Classic Nightmare" },
        { "u(6646)",  "Mousie Madness" },
        { "u(7037)",  "Double Dragon 2" },
        { "u(7287)",  "Big Extreme" },
        { "u(7316)",  "Butcher" },
        { "u(7526)",  "Electric Chair" },
        { "u(7654)",  "Final Strike" },
        { "u(7766)",  "Fast Mode 1" },
        { "u(7768)",  "Fast Mode 3" },
        { "u(8269)",  "4 Floor Fun" },
        { "u(8451)",  "KA Wooden With Water" },
        { "u(8874)",  "America the Wet" },
        { "u(9082)",  "Adrenalizer" },
    };
    // clang-format on

    std::optional<std::string_view> GetDeluxeTrackDesignName(std::string_view rawName)
    {
        for (const auto& [id, name] : kDeluxeTrackDesignNames)
        {
            if (rawName == id)
            {
                return name;
            }
        }
        return std::nullopt;
    }
} // namespace OpenRCT2::RCT1
