#include "SurfaceData.h"

#include "Surface.h"
#include "tile_element/Slope.h"

// 0x00981A1E
// Table of pre-calculated surface slopes (32) when raising the land tile for a given selection (5)
// 0x1F = new slope
// 0x20 = base height increases
constexpr uint8_t TileElementRaiseStyles[9][32] = {
    // MAP_SELECT_TYPE_CORNER_0
    { kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_CORNER_1
    { kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_CORNER_2
    { kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_CORNER_3
    { kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_FULL
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT },
    // MAP_SELECT_TYPE_EDGE_0
    { kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_EDGE_1
    { kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_EDGE_2
    { kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp },
    // MAP_SELECT_TYPE_EDGE_3
    { kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp },

};

// 0x00981ABE
// Basically the inverse of the table above.
// 0x1F = new slope
// 0x20 = base height increases
constexpr uint8_t TileElementLowerStyles[9][32] = {
    // MAP_SELECT_TYPE_CORNER_0
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      0,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_CORNER_1
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      0,
      kTileSlopeNCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_CORNER_2
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeWCornerUp,
      0,
      kTileSlopeNCornerUp,
      kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_CORNER_3
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeSCornerUp,
      0,
      kTileSlopeNCornerUp,
      kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp
          | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeDiagonalFlag | kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_FULL
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      0,
      0,
      0,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      0,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      0 },
    // MAP_SELECT_TYPE_EDGE_0
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      0,
      kTileSlopeNCornerUp,
      kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      0,
      kTileSlopeNCornerUp,
      kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      0,
      kTileSlopeNCornerUp,
      kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeECornerUp,
      0,
      kTileSlopeNCornerUp,
      kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      0,
      kTileSlopeNCornerUp,
      kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp,
      0,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp },
    // MAP_SELECT_TYPE_EDGE_1
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      0,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      0,
      0,
      kTileSlopeECornerUp,
      kTileSlopeECornerUp,
      kTileSlopeSCornerUp,
      kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      0,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      0,
      0,
      kTileSlopeECornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp },
    // MAP_SELECT_TYPE_EDGE_2
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      0,
      0,
      0,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp,
      kTileSlopeSCornerUp,
      kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      0,
      0,
      0,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp,
      kTileSlopeSCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeSCornerUp | kTileSlopeWCornerUp },
    // MAP_SELECT_TYPE_EDGE_3
    { SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      0,
      kTileSlopeNCornerUp,
      0,
      kTileSlopeNCornerUp,
      0,
      kTileSlopeNCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      0,
      kTileSlopeNCornerUp,
      0,
      kTileSlopeNCornerUp,
      0,
      kTileSlopeNCornerUp | kTileSlopeECornerUp | kTileSlopeSCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT | kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp,
      kTileSlopeECornerUp | kTileSlopeSCornerUp | kTileSlopeWCornerUp,
      kTileSlopeNCornerUp | kTileSlopeWCornerUp },
};

uint8_t LowerSurfaceCornerFlags(size_t SelectedCorner, size_t CurrentSlope)
{
    return TileElementLowerStyles[SelectedCorner][CurrentSlope];
}

uint8_t RaiseSurfaceCornerFlags(size_t SelectedCorner, size_t CurrentSlope)
{
    return TileElementRaiseStyles[SelectedCorner][CurrentSlope];
}
