/*****************************************************************************
 * Copyright (c) 2014-2024 OpenRCT2 developers
 *
 * For a complete list of all authors, please refer to contributors.md
 * Interested in contributing? Visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is licensed under the GNU General Public License version 3.
 *****************************************************************************/

#include "../../../ride/Track.h"
#include "../../../ride/TrackPaint.h"
#include "../../../sprites.h"
#include "../../tile_element/Paint.Tunnel.h"
#include "../../tile_element/Segment.h"
#include "WoodenRollerCoaster.hpp"

using namespace OpenRCT2;

// static constexpr TunnelGroup kTunnelGroup = TunnelGroup::Square;

enum
{
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_0 = SPR_CSG_BEGIN + 65447,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_1 = SPR_CSG_BEGIN + 65448,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_2 = SPR_CSG_BEGIN + 65449,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_3 = SPR_CSG_BEGIN + 65450,

    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_0 = SPR_CSG_BEGIN + 65451,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_1 = SPR_CSG_BEGIN + 65452,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_2 = SPR_CSG_BEGIN + 65453,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_3 = SPR_CSG_BEGIN + 65454,

    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_0 = SPR_CSG_BEGIN + 65455,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_1 = SPR_CSG_BEGIN + 65456,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_2 = SPR_CSG_BEGIN + 65457,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_3 = SPR_CSG_BEGIN + 65458,

    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_0 = SPR_CSG_BEGIN + 65459,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_1 = SPR_CSG_BEGIN + 65460,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_2 = SPR_CSG_BEGIN + 65461,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_3 = SPR_CSG_BEGIN + 65462,

    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_0 = SPR_CSG_BEGIN + 65463,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_1 = SPR_CSG_BEGIN + 65464,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_2 = SPR_CSG_BEGIN + 65465,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_3 = SPR_CSG_BEGIN + 65466,

    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_0 = SPR_CSG_BEGIN + 65467,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_1 = SPR_CSG_BEGIN + 65468,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_2 = SPR_CSG_BEGIN + 65469,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_3 = SPR_CSG_BEGIN + 65470,

    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_0 = SPR_CSG_BEGIN + 65471,
    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_1 = SPR_CSG_BEGIN + 65472,
    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_2 = SPR_CSG_BEGIN + 65473,
    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_3 = SPR_CSG_BEGIN + 65474,

    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_FRONT_1 = SPR_CSG_BEGIN + 65475,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_FRONT_3 = SPR_CSG_BEGIN + 65476,

    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_FRONT_2 = SPR_CSG_BEGIN + 65477,

    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_FRONT_1 = SPR_CSG_BEGIN + 65478,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_FRONT_2 = SPR_CSG_BEGIN + 65479,

    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_FRONT_1 = SPR_CSG_BEGIN + 65480,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_FRONT_2 = SPR_CSG_BEGIN + 65481,

    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_FRONT_1 = SPR_CSG_BEGIN + 65482,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_FRONT_2 = SPR_CSG_BEGIN + 65483,

    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_FRONT_1 = SPR_CSG_BEGIN + 65484,
    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_FRONT_2 = SPR_CSG_BEGIN + 65485,

    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_FRONT_0 = SPR_CSG_BEGIN + 65486,

    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_0_0 = SPR_CSG_BEGIN + 65585,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_1_0 = SPR_CSG_BEGIN + 65586,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_2_0 = SPR_CSG_BEGIN + 65587,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_3_0 = SPR_CSG_BEGIN + 65588,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_4_0 = SPR_CSG_BEGIN + 65589,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_0_1 = SPR_CSG_BEGIN + 65590,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_1_1 = SPR_CSG_BEGIN + 65591,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_2_1 = SPR_CSG_BEGIN + 65592,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_3_1 = SPR_CSG_BEGIN + 65593,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_4_1 = SPR_CSG_BEGIN + 65594,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_0_2 = SPR_CSG_BEGIN + 65595,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_1_2 = SPR_CSG_BEGIN + 65596,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_2_2 = SPR_CSG_BEGIN + 65597,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_3_2 = SPR_CSG_BEGIN + 65598,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_4_2 = SPR_CSG_BEGIN + 65599,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_0_3 = SPR_CSG_BEGIN + 65600,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_1_3 = SPR_CSG_BEGIN + 65601,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_2_3 = SPR_CSG_BEGIN + 65602,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_3_3 = SPR_CSG_BEGIN + 65603,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_4_3 = SPR_CSG_BEGIN + 65604,

    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_0_0 = SPR_CSG_BEGIN + 65605,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_1_0 = SPR_CSG_BEGIN + 65606,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_2_0 = SPR_CSG_BEGIN + 65607,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_3_0 = SPR_CSG_BEGIN + 65608,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_4_0 = SPR_CSG_BEGIN + 65609,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_0_2 = SPR_CSG_BEGIN + 65610,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_1_2 = SPR_CSG_BEGIN + 65611,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_2_2 = SPR_CSG_BEGIN + 65612,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_3_2 = SPR_CSG_BEGIN + 65613,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_4_2 = SPR_CSG_BEGIN + 65614,

    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_0_0 = SPR_CSG_BEGIN + 65615,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_1_0 = SPR_CSG_BEGIN + 65616,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_2_0 = SPR_CSG_BEGIN + 65617,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_3_0 = SPR_CSG_BEGIN + 65618,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_4_0 = SPR_CSG_BEGIN + 65619,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_0_1 = SPR_CSG_BEGIN + 65620,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_1_1 = SPR_CSG_BEGIN + 65621,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_2_1 = SPR_CSG_BEGIN + 65622,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_3_1 = SPR_CSG_BEGIN + 65623,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_4_1 = SPR_CSG_BEGIN + 65624,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_0_2 = SPR_CSG_BEGIN + 65625,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_1_2 = SPR_CSG_BEGIN + 65626,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_2_2 = SPR_CSG_BEGIN + 65627,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_3_2 = SPR_CSG_BEGIN + 65628,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_4_2 = SPR_CSG_BEGIN + 65629,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_0_3 = SPR_CSG_BEGIN + 65630,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_1_3 = SPR_CSG_BEGIN + 65631,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_2_3 = SPR_CSG_BEGIN + 65632,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_3_3 = SPR_CSG_BEGIN + 65633,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_4_3 = SPR_CSG_BEGIN + 65634,

    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_0_0 = SPR_CSG_BEGIN + 65635,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_1_0 = SPR_CSG_BEGIN + 65636,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_2_0 = SPR_CSG_BEGIN + 65637,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_3_0 = SPR_CSG_BEGIN + 65638,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_4_0 = SPR_CSG_BEGIN + 65639,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_0_2 = SPR_CSG_BEGIN + 65640,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_1_2 = SPR_CSG_BEGIN + 65641,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_2_2 = SPR_CSG_BEGIN + 65642,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_3_2 = SPR_CSG_BEGIN + 65643,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_4_2 = SPR_CSG_BEGIN + 65644,

    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_4_3 = SPR_CSG_BEGIN + 65645,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_3_3 = SPR_CSG_BEGIN + 65646,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_2_3 = SPR_CSG_BEGIN + 65647,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_1_3 = SPR_CSG_BEGIN + 65648,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_0_3 = SPR_CSG_BEGIN + 65649,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_4_0 = SPR_CSG_BEGIN + 65650,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_3_0 = SPR_CSG_BEGIN + 65651,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_2_0 = SPR_CSG_BEGIN + 65652,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_1_0 = SPR_CSG_BEGIN + 65653,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_0_0 = SPR_CSG_BEGIN + 65654,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_4_1 = SPR_CSG_BEGIN + 65655,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_3_1 = SPR_CSG_BEGIN + 65656,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_2_1 = SPR_CSG_BEGIN + 65657,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_1_1 = SPR_CSG_BEGIN + 65658,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_0_1 = SPR_CSG_BEGIN + 65659,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_4_2 = SPR_CSG_BEGIN + 65660,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_3_2 = SPR_CSG_BEGIN + 65661,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_2_2 = SPR_CSG_BEGIN + 65662,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_1_2 = SPR_CSG_BEGIN + 65663,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_0_2 = SPR_CSG_BEGIN + 65664,

    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_4_3 = SPR_CSG_BEGIN + 65665,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_3_3 = SPR_CSG_BEGIN + 65666,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_2_3 = SPR_CSG_BEGIN + 65667,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_1_3 = SPR_CSG_BEGIN + 65668,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_0_3 = SPR_CSG_BEGIN + 65669,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_4_1 = SPR_CSG_BEGIN + 65670,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_3_1 = SPR_CSG_BEGIN + 65671,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_2_1 = SPR_CSG_BEGIN + 65672,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_1_1 = SPR_CSG_BEGIN + 65673,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_0_1 = SPR_CSG_BEGIN + 65674,

    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_2_3 = SPR_CSG_BEGIN + 65849,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_1_3 = SPR_CSG_BEGIN + 65850,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_0_3 = SPR_CSG_BEGIN + 65851,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_2_0 = SPR_CSG_BEGIN + 65852,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_1_0 = SPR_CSG_BEGIN + 65853,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_0_0 = SPR_CSG_BEGIN + 65854,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_2_1 = SPR_CSG_BEGIN + 65855,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_1_1 = SPR_CSG_BEGIN + 65856,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_0_1 = SPR_CSG_BEGIN + 65857,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_2_2 = SPR_CSG_BEGIN + 65858,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_1_2 = SPR_CSG_BEGIN + 65859,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_0_2 = SPR_CSG_BEGIN + 65860,

    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_2_3 = SPR_CSG_BEGIN + 65861,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_1_3 = SPR_CSG_BEGIN + 65862,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_0_3 = SPR_CSG_BEGIN + 65863,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_2_1 = SPR_CSG_BEGIN + 65864,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_1_1 = SPR_CSG_BEGIN + 65865,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_0_1 = SPR_CSG_BEGIN + 65866,

    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_2_3 = SPR_CSG_BEGIN + 65885,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_1_3 = SPR_CSG_BEGIN + 65886,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_0_3 = SPR_CSG_BEGIN + 65887,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_2_0 = SPR_CSG_BEGIN + 65888,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_1_0 = SPR_CSG_BEGIN + 65889,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_0_0 = SPR_CSG_BEGIN + 65890,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_2_1 = SPR_CSG_BEGIN + 65891,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_1_1 = SPR_CSG_BEGIN + 65892,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_0_1 = SPR_CSG_BEGIN + 65893,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_2_2 = SPR_CSG_BEGIN + 65894,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_1_2 = SPR_CSG_BEGIN + 65895,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_0_2 = SPR_CSG_BEGIN + 65896,

    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_2_3 = SPR_CSG_BEGIN + 65897,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_1_3 = SPR_CSG_BEGIN + 65898,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_0_3 = SPR_CSG_BEGIN + 65899,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_2_1 = SPR_CSG_BEGIN + 65900,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_1_1 = SPR_CSG_BEGIN + 65901,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_0_1 = SPR_CSG_BEGIN + 65902,

    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_HANDRAIL_0 = SPR_CSG_BEGIN + 66203,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_HANDRAIL_1 = SPR_CSG_BEGIN + 66204,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_HANDRAIL_2 = SPR_CSG_BEGIN + 66205,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_HANDRAIL_3 = SPR_CSG_BEGIN + 66206,

    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_HANDRAIL_0 = SPR_CSG_BEGIN + 66207,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_HANDRAIL_1 = SPR_CSG_BEGIN + 66208,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_HANDRAIL_2 = SPR_CSG_BEGIN + 66209,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_HANDRAIL_3 = SPR_CSG_BEGIN + 66210,

    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_HANDRAIL_0 = SPR_CSG_BEGIN + 66211,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_HANDRAIL_1 = SPR_CSG_BEGIN + 66212,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_HANDRAIL_2 = SPR_CSG_BEGIN + 66213,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_HANDRAIL_3 = SPR_CSG_BEGIN + 66214,

    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_HANDRAIL_0 = SPR_CSG_BEGIN + 66215,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_HANDRAIL_1 = SPR_CSG_BEGIN + 66216,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_HANDRAIL_2 = SPR_CSG_BEGIN + 66217,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_HANDRAIL_3 = SPR_CSG_BEGIN + 66218,

    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_HANDRAIL_0 = SPR_CSG_BEGIN + 66219,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_HANDRAIL_1 = SPR_CSG_BEGIN + 66220,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_HANDRAIL_2 = SPR_CSG_BEGIN + 66221,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_HANDRAIL_3 = SPR_CSG_BEGIN + 66222,

    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_HANDRAIL_0 = SPR_CSG_BEGIN + 66223,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_HANDRAIL_1 = SPR_CSG_BEGIN + 66224,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_HANDRAIL_2 = SPR_CSG_BEGIN + 66225,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_HANDRAIL_3 = SPR_CSG_BEGIN + 66226,

    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_HANDRAIL_0 = SPR_CSG_BEGIN + 66227,
    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_HANDRAIL_1 = SPR_CSG_BEGIN + 66228,
    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_HANDRAIL_2 = SPR_CSG_BEGIN + 66229,
    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_HANDRAIL_3 = SPR_CSG_BEGIN + 66230,

    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_FRONT_HANDRAIL_1 = SPR_CSG_BEGIN + 66231,
    SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_FRONT_HANDRAIL_3 = SPR_CSG_BEGIN + 66232,

    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_FRONT_HANDRAIL_2 = SPR_CSG_BEGIN + 66233,

    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_FRONT_HANDRAIL_1 = SPR_CSG_BEGIN + 66234,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_FRONT_HANDRAIL_2 = SPR_CSG_BEGIN + 66235,

    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_FRONT_HANDRAIL_1 = SPR_CSG_BEGIN + 66236,
    SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_FRONT_HANDRAIL_2 = SPR_CSG_BEGIN + 66237,

    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_FRONT_HANDRAIL_1 = SPR_CSG_BEGIN + 66238,
    SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_FRONT_HANDRAIL_2 = SPR_CSG_BEGIN + 66239,

    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_FRONT_HANDRAIL_1 = SPR_CSG_BEGIN + 66240,
    SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_FRONT_HANDRAIL_2 = SPR_CSG_BEGIN + 66241,

    SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_FRONT_HANDRAIL_0 = SPR_CSG_BEGIN + 66242,

    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_0_0 = SPR_CSG_BEGIN + 66341,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_1_0 = SPR_CSG_BEGIN + 66342,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_2_0 = SPR_CSG_BEGIN + 66343,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_3_0 = SPR_CSG_BEGIN + 66344,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_4_0 = SPR_CSG_BEGIN + 66345,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_0_1 = SPR_CSG_BEGIN + 66346,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_1_1 = SPR_CSG_BEGIN + 66347,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_2_1 = SPR_CSG_BEGIN + 66348,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_3_1 = SPR_CSG_BEGIN + 66349,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_4_1 = SPR_CSG_BEGIN + 66350,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_0_2 = SPR_CSG_BEGIN + 66351,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_1_2 = SPR_CSG_BEGIN + 66352,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_2_2 = SPR_CSG_BEGIN + 66353,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_3_2 = SPR_CSG_BEGIN + 66354,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_4_2 = SPR_CSG_BEGIN + 66355,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_0_3 = SPR_CSG_BEGIN + 66356,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_1_3 = SPR_CSG_BEGIN + 66357,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_2_3 = SPR_CSG_BEGIN + 66358,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_3_3 = SPR_CSG_BEGIN + 66359,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_4_3 = SPR_CSG_BEGIN + 66360,

    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_0_0 = SPR_CSG_BEGIN + 66361,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_1_0 = SPR_CSG_BEGIN + 66362,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_2_0 = SPR_CSG_BEGIN + 66363,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_3_0 = SPR_CSG_BEGIN + 66364,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_4_0 = SPR_CSG_BEGIN + 66365,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_0_2 = SPR_CSG_BEGIN + 66366,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_1_2 = SPR_CSG_BEGIN + 66367,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_2_2 = SPR_CSG_BEGIN + 66368,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_3_2 = SPR_CSG_BEGIN + 66369,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_4_2 = SPR_CSG_BEGIN + 66370,

    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_0 = SPR_CSG_BEGIN + 66371,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_0 = SPR_CSG_BEGIN + 66372,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_0 = SPR_CSG_BEGIN + 66373,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_0 = SPR_CSG_BEGIN + 66374,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_0 = SPR_CSG_BEGIN + 66375,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_1 = SPR_CSG_BEGIN + 66376,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_1 = SPR_CSG_BEGIN + 66377,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_1 = SPR_CSG_BEGIN + 66378,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_1 = SPR_CSG_BEGIN + 66379,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_1 = SPR_CSG_BEGIN + 66380,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_2 = SPR_CSG_BEGIN + 66381,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_2 = SPR_CSG_BEGIN + 66382,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_2 = SPR_CSG_BEGIN + 66383,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_2 = SPR_CSG_BEGIN + 66384,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_2 = SPR_CSG_BEGIN + 66385,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_3 = SPR_CSG_BEGIN + 66386,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_3 = SPR_CSG_BEGIN + 66387,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_3 = SPR_CSG_BEGIN + 66388,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_3 = SPR_CSG_BEGIN + 66389,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_3 = SPR_CSG_BEGIN + 66390,

    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_0_0 = SPR_CSG_BEGIN + 66391,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_1_0 = SPR_CSG_BEGIN + 66392,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_2_0 = SPR_CSG_BEGIN + 66393,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_3_0 = SPR_CSG_BEGIN + 66394,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_4_0 = SPR_CSG_BEGIN + 66395,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_0_2 = SPR_CSG_BEGIN + 66396,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_1_2 = SPR_CSG_BEGIN + 66397,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_2_2 = SPR_CSG_BEGIN + 66398,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_3_2 = SPR_CSG_BEGIN + 66399,
    SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_4_2 = SPR_CSG_BEGIN + 66400,

    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_3 = SPR_CSG_BEGIN + 66401,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_3 = SPR_CSG_BEGIN + 66402,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_3 = SPR_CSG_BEGIN + 66403,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_3 = SPR_CSG_BEGIN + 66404,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_3 = SPR_CSG_BEGIN + 66405,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_0 = SPR_CSG_BEGIN + 66406,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_0 = SPR_CSG_BEGIN + 66407,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_0 = SPR_CSG_BEGIN + 66408,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_0 = SPR_CSG_BEGIN + 66409,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_0 = SPR_CSG_BEGIN + 66410,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_1 = SPR_CSG_BEGIN + 66411,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_1 = SPR_CSG_BEGIN + 66412,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_1 = SPR_CSG_BEGIN + 66413,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_1 = SPR_CSG_BEGIN + 66414,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_1 = SPR_CSG_BEGIN + 66415,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_2 = SPR_CSG_BEGIN + 66416,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_2 = SPR_CSG_BEGIN + 66417,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_2 = SPR_CSG_BEGIN + 66418,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_2 = SPR_CSG_BEGIN + 66419,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_2 = SPR_CSG_BEGIN + 66420,

    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_4_3 = SPR_CSG_BEGIN + 66421,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_3_3 = SPR_CSG_BEGIN + 66422,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_2_3 = SPR_CSG_BEGIN + 66423,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_1_3 = SPR_CSG_BEGIN + 66424,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_0_3 = SPR_CSG_BEGIN + 66425,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_4_1 = SPR_CSG_BEGIN + 66426,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_3_1 = SPR_CSG_BEGIN + 66427,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_2_1 = SPR_CSG_BEGIN + 66428,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_1_1 = SPR_CSG_BEGIN + 66429,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_0_1 = SPR_CSG_BEGIN + 66430,

    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_2_3 = SPR_CSG_BEGIN + 66605,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_1_3 = SPR_CSG_BEGIN + 66606,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_0_3 = SPR_CSG_BEGIN + 66607,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_2_0 = SPR_CSG_BEGIN + 66608,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_1_0 = SPR_CSG_BEGIN + 66609,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_0_0 = SPR_CSG_BEGIN + 66610,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_2_1 = SPR_CSG_BEGIN + 66611,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_1_1 = SPR_CSG_BEGIN + 66612,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_0_1 = SPR_CSG_BEGIN + 66613,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_2_2 = SPR_CSG_BEGIN + 66614,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_1_2 = SPR_CSG_BEGIN + 66615,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_0_2 = SPR_CSG_BEGIN + 66616,

    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_2_3 = SPR_CSG_BEGIN + 66617,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_1_3 = SPR_CSG_BEGIN + 66618,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_0_3 = SPR_CSG_BEGIN + 66619,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_2_1 = SPR_CSG_BEGIN + 66620,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_1_1 = SPR_CSG_BEGIN + 66621,
    SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_0_1 = SPR_CSG_BEGIN + 66622,

    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_2_3 = SPR_CSG_BEGIN + 66641,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_1_3 = SPR_CSG_BEGIN + 66642,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_0_3 = SPR_CSG_BEGIN + 66643,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_2_0 = SPR_CSG_BEGIN + 66644,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_1_0 = SPR_CSG_BEGIN + 66645,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_0_0 = SPR_CSG_BEGIN + 66646,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_2_1 = SPR_CSG_BEGIN + 66647,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_1_1 = SPR_CSG_BEGIN + 66648,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_0_1 = SPR_CSG_BEGIN + 66649,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_2_2 = SPR_CSG_BEGIN + 66650,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_1_2 = SPR_CSG_BEGIN + 66651,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_0_2 = SPR_CSG_BEGIN + 66652,

    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_2_3 = SPR_CSG_BEGIN + 66653,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_1_3 = SPR_CSG_BEGIN + 66654,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_0_3 = SPR_CSG_BEGIN + 66655,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_2_1 = SPR_CSG_BEGIN + 66656,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_1_1 = SPR_CSG_BEGIN + 66657,
    SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_0_1 = SPR_CSG_BEGIN + 66658,
};

static constexpr std::array<StraightWoodenTrack, kNumOrthogonalDirections> kFlatToLeftBankImages = { {
    {
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_0,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_HANDRAIL_0,
    },
    {
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_1,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_HANDRAIL_1,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_FRONT_1,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_FRONT_HANDRAIL_1,
    },
    {
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_2,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_HANDRAIL_2,
    },
    {
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_3,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_HANDRAIL_3,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_FRONT_3,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_LEFT_BANK_FRONT_HANDRAIL_3,
    },
} };

static constexpr std::array<StraightWoodenTrack, kNumOrthogonalDirections> kFlatToRightBankImages = { {
    {
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_0,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_HANDRAIL_0,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_FRONT_0,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_FRONT_HANDRAIL_0,
    },
    {
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_1,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_HANDRAIL_1,
    },
    {
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_2,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_HANDRAIL_2,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_FRONT_2,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_FRONT_HANDRAIL_2,
    },
    {
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_3,
        SPR_CLASSIC_WOODEN_RC_FLAT_TO_RIGHT_BANK_HANDRAIL_3,
    },
} };

static constexpr std::array<StraightWoodenTrack, kNumOrthogonalDirections> kLeftBankImages = { {
    { SPR_CLASSIC_WOODEN_RC_LEFT_BANK_0, SPR_CLASSIC_WOODEN_RC_LEFT_BANK_HANDRAIL_0 },
    { SPR_CLASSIC_WOODEN_RC_LEFT_BANK_1, SPR_CLASSIC_WOODEN_RC_LEFT_BANK_HANDRAIL_1 },
    { SPR_CLASSIC_WOODEN_RC_LEFT_BANK_2, SPR_CLASSIC_WOODEN_RC_LEFT_BANK_HANDRAIL_2 },
    { SPR_CLASSIC_WOODEN_RC_LEFT_BANK_3, SPR_CLASSIC_WOODEN_RC_LEFT_BANK_HANDRAIL_3 },
} };

static constexpr std::array<StraightWoodenTrack, kNumOrthogonalDirections> kUp25ToLeftBankImages = { {
    {
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_0,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_HANDRAIL_0,
    },
    {
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_1,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_HANDRAIL_1,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_FRONT_1,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_FRONT_HANDRAIL_1,
    },
    {
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_2,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_HANDRAIL_2,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_FRONT_2,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_FRONT_HANDRAIL_2,
    },
    {
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_3,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_LEFT_BANK_HANDRAIL_3,
    },
} };

static constexpr std::array<StraightWoodenTrack, kNumOrthogonalDirections> kUp25ToRightBankImages = { {
    {
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_0,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_HANDRAIL_0,
    },
    {
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_1,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_HANDRAIL_1,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_FRONT_1,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_FRONT_HANDRAIL_1,
    },
    {
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_2,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_HANDRAIL_2,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_FRONT_2,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_FRONT_HANDRAIL_2,
    },
    {
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_3,
        SPR_CLASSIC_WOODEN_RC_UP25_TO_RIGHT_BANK_HANDRAIL_3,
    },
} };

static constexpr std::array<StraightWoodenTrack, kNumOrthogonalDirections> kLeftBankToUp25Images = { {
    {
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_0,
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_HANDRAIL_0,
    },
    {
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_1,
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_HANDRAIL_1,
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_FRONT_1,
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_FRONT_HANDRAIL_1,
    },
    {
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_2,
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_HANDRAIL_2,
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_FRONT_2,
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_FRONT_HANDRAIL_2,
    },
    {
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_3,
        SPR_CLASSIC_WOODEN_RC_LEFT_BANK_TO_UP25_HANDRAIL_3,
    },
} };

static constexpr std::array<StraightWoodenTrack, kNumOrthogonalDirections> kRightBankToUp25Images = { {
    {
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_0,
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_HANDRAIL_0,
    },
    {
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_1,
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_HANDRAIL_1,
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_FRONT_1,
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_FRONT_HANDRAIL_1,
    },
    {
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_2,
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_HANDRAIL_2,
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_FRONT_2,
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_FRONT_HANDRAIL_2,
    },
    {
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_3,
        SPR_CLASSIC_WOODEN_RC_RIGHT_BANK_TO_UP25_HANDRAIL_3,
    },
} };

static constexpr std::array<std::array<StraightWoodenTrack, kNumOrthogonalDirections>, 3> kBankedQuarterTurn3Images = { {
    { {
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_0_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_0_0,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_0_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_0_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_0_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_0_1,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_0_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_0_2,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_0_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_0_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_0_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_0_3,
        },
    } },
    { {
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_1_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_1_0,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_1_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_1_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_1_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_1_1,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_1_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_1_2,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_1_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_1_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_1_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_1_3,
        },
    } },
    { {
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_2_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_2_0,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_2_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_2_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_2_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_2_1,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_2_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_2_2,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_2_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_HANDRAIL_2_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_2_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_3_FRONT_HANDRAIL_2_3,
        },
    } },
} };

static constexpr std::array<std::array<StraightWoodenTrack, kNumOrthogonalDirections>, 5> kBankedQuarterTurn5Images = { {
    { {
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_0_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_0_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_0_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_0_0,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_0_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_0_1,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_0_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_0_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_0_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_0_2,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_0_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_0_3,
        },
    } },
    { {
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_1_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_1_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_1_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_1_0,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_1_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_1_1,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_1_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_1_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_1_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_1_2,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_1_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_1_3,
        },
    } },
    { {
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_2_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_2_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_2_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_2_0,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_2_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_2_1,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_2_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_2_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_2_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_2_2,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_2_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_2_3,
        },
    } },
    { {
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_3_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_3_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_3_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_3_0,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_3_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_3_1,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_3_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_3_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_3_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_3_2,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_3_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_3_3,
        },
    } },
    { {
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_4_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_4_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_4_0,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_4_0,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_4_1,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_4_1,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_4_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_4_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_4_2,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_FRONT_HANDRAIL_4_2,
        },
        {
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_4_3,
            SPR_CLASSIC_WOODEN_RC_BANKED_QUARTER_TURN_5_HANDRAIL_4_3,
        },
    } },
} };

static constexpr std::array<std::array<StraightWoodenTrack, kNumOrthogonalDirections>, 3> kLeftHalfBankedHelixUpSmallImages = {
    {
        { {
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_0_0,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_0_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_0_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_0_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_0_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_0_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_0_2,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_0_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_0_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_0_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_0_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_0_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_1_0,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_1_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_1_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_1_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_1_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_1_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_1_2,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_1_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_1_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_1_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_1_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_1_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_2_0,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_2_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_2_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_2_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_2_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_2_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_2_2,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_2_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_2_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_HANDRAIL_2_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_2_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_UP_SMALL_FRONT_HANDRAIL_2_3,
            },
        } },
    }
};

static constexpr std::array<std::array<StraightWoodenTrack, kNumOrthogonalDirections>, 5> kLeftHalfBankedHelixUpLargeImages = {
    {
        { {
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_0_0,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_0_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_0_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_0_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_0_2,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_0_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_0_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_0_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_1_0,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_1_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_1_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_1_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_1_2,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_1_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_1_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_1_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_2_0,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_2_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_2_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_2_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_2_2,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_2_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_2_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_2_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_3_0,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_3_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_3_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_3_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_3_2,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_3_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_3_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_3_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_4_0,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_4_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_4_1,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_4_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_4_2,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_4_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_4_3,
                SPR_CLASSIC_WOODEN_RC_LEFT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_4_3,
            },
        } },
    }
};

static constexpr std::array<std::array<StraightWoodenTrack, kNumOrthogonalDirections>, 5> kRightHalfBankedHelixUpLargeImages = {
    {
        { {
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_0_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_0_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_0_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_0_1,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_0_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_0_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_0_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_0_3,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_0_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_1_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_1_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_1_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_1_1,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_1_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_1_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_1_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_1_3,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_1_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_2_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_2_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_2_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_2_1,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_2_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_2_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_2_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_2_3,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_2_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_3_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_3_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_3_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_3_1,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_3_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_3_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_3_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_3_3,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_3_3,
            },
        } },
        { {
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_4_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_4_0,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_4_0,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_4_1,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_1,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_4_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_4_2,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_FRONT_HANDRAIL_4_2,
            },
            {
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_4_3,
                SPR_CLASSIC_WOODEN_RC_RIGHT_HALF_BANKED_HELIX_LARGE_UP_HANDRAIL_4_3,
            },
        } },
    }
};

static void ClassicWoodenTwisterRCTrackLeftBankToFlat(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    WoodenRCTrackFlatToBank<false, kFlatToRightBankImages>(
        session, ride, trackSequence, DirectionReverse(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrackRightBankToFlat(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    WoodenRCTrackFlatToBank<false, kFlatToLeftBankImages>(
        session, ride, trackSequence, DirectionReverse(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrackRightBank(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    WoodenRCTrackFlatToBank<false, kLeftBankImages>(
        session, ride, trackSequence, DirectionReverse(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrackLeftBankTo25DegDown(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    WoodenRCTrack25DegUpToBank<false, kUp25ToRightBankImages>(
        session, ride, trackSequence, DirectionReverse(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrackRightBankTo25DegDown(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    WoodenRCTrack25DegUpToBank<false, kUp25ToLeftBankImages>(
        session, ride, trackSequence, DirectionReverse(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrack25DegDownToLeftBank(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    WoodenRCTrackBankTo25DegUp<false, kRightBankToUp25Images>(
        session, ride, trackSequence, DirectionReverse(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrack25DegDownToRightBank(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    WoodenRCTrackBankTo25DegUp<false, kLeftBankToUp25Images>(
        session, ride, trackSequence, DirectionReverse(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrackRightQuarterTurn3Bank(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    trackSequence = kMapLeftQuarterTurn3TilesToRightQuarterTurn3Tiles[trackSequence];
    WoodenRCTrackLeftQuarterTurn3Bank<false, kBankedQuarterTurn3Images>(
        session, ride, trackSequence, DirectionPrev(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrackBankedLeftQuarterTurn5(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    trackSequence = kMapLeftQuarterTurn5TilesToRightQuarterTurn5Tiles[trackSequence];
    WoodenRCTrackBankedRightQuarterTurn5<false, kBankedQuarterTurn5Images>(
        session, ride, trackSequence, DirectionNext(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrackRightHalfBankedHelixDownSmall(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    if (trackSequence >= 4)
    {
        trackSequence -= 4;
        direction = DirectionNext(direction);
    }
    trackSequence = kMapLeftQuarterTurn3TilesToRightQuarterTurn3Tiles[trackSequence];
    WoodenRCTrackLeftHalfBankedHelixUpSmall<false, kLeftHalfBankedHelixUpSmallImages>(
        session, ride, trackSequence, DirectionPrev(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrackLeftHalfBankedHelixDownLarge(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    if (trackSequence >= 7)
    {
        trackSequence -= 7;
        direction = DirectionPrev(direction);
    }
    trackSequence = kMapLeftQuarterTurn5TilesToRightQuarterTurn5Tiles[trackSequence];
    WoodenRCTrackRightHalfBankedHelixUpLarge<false, kRightHalfBankedHelixUpLargeImages>(
        session, ride, trackSequence, DirectionNext(direction), height, trackElement, supportType);
}

static void ClassicWoodenTwisterRCTrackRightHalfBankedHelixDownLarge(
    PaintSession& session, const Ride& ride, uint8_t trackSequence, uint8_t direction, int32_t height,
    const TrackElement& trackElement, SupportType supportType)
{
    if (trackSequence >= 7)
    {
        trackSequence -= 7;
        direction = DirectionNext(direction);
    }
    trackSequence = kMapLeftQuarterTurn5TilesToRightQuarterTurn5Tiles[trackSequence];
    WoodenRCTrackLeftHalfBankedHelixUpLarge<false, kLeftHalfBankedHelixUpLargeImages>(
        session, ride, trackSequence, DirectionPrev(direction), height, trackElement, supportType);
}

// Stylistically, this coaster is _very_ similar to the regular Wooden Roller Coaster.
// The only difference is the degree of the banking.
// As such, all non-banked pieces are simply drawn as regular wooden roller coaster pieces.
TRACK_PAINT_FUNCTION GetTrackPaintFunctionClassicWoodenTwisterRC(OpenRCT2::TrackElemType trackType)
{
    if (!IsCsgLoaded())
    {
        return GetTrackPaintFunctionWoodenRC(trackType);
    }

    switch (trackType)
    {
        case TrackElemType::FlatToLeftBank:
            return WoodenRCTrackFlatToBank<false, kFlatToLeftBankImages>;
        case TrackElemType::FlatToRightBank:
            return WoodenRCTrackFlatToBank<false, kFlatToRightBankImages>;
        case TrackElemType::LeftBankToFlat:
            return ClassicWoodenTwisterRCTrackLeftBankToFlat;
        case TrackElemType::RightBankToFlat:
            return ClassicWoodenTwisterRCTrackRightBankToFlat;
        case TrackElemType::LeftBank:
            return WoodenRCTrackFlatToBank<false, kLeftBankImages>;
        case TrackElemType::RightBank:
            return ClassicWoodenTwisterRCTrackRightBank;
        case TrackElemType::Up25ToLeftBank:
            return WoodenRCTrack25DegUpToBank<false, kUp25ToLeftBankImages>;
        case TrackElemType::Up25ToRightBank:
            return WoodenRCTrack25DegUpToBank<false, kUp25ToRightBankImages>;
        case TrackElemType::LeftBankToDown25:
            return ClassicWoodenTwisterRCTrackLeftBankTo25DegDown;
        case TrackElemType::RightBankToDown25:
            return ClassicWoodenTwisterRCTrackRightBankTo25DegDown;

        case TrackElemType::LeftBankToUp25:
            return WoodenRCTrackBankTo25DegUp<false, kLeftBankToUp25Images>;
        case TrackElemType::RightBankToUp25:
            return WoodenRCTrackBankTo25DegUp<false, kRightBankToUp25Images>;
        case TrackElemType::Down25ToLeftBank:
            return ClassicWoodenTwisterRCTrack25DegDownToLeftBank;
        case TrackElemType::Down25ToRightBank:
            return ClassicWoodenTwisterRCTrack25DegDownToRightBank;

        case TrackElemType::LeftBankedQuarterTurn3Tiles:
            return WoodenRCTrackLeftQuarterTurn3Bank<false, kBankedQuarterTurn3Images>;
        case TrackElemType::RightBankedQuarterTurn3Tiles:
            return ClassicWoodenTwisterRCTrackRightQuarterTurn3Bank;

        case TrackElemType::BankedLeftQuarterTurn5Tiles:
            return ClassicWoodenTwisterRCTrackBankedLeftQuarterTurn5;
        case TrackElemType::BankedRightQuarterTurn5Tiles:
            return WoodenRCTrackBankedRightQuarterTurn5<false, kBankedQuarterTurn5Images>;

        case TrackElemType::LeftHalfBankedHelixUpSmall:
            return WoodenRCTrackLeftHalfBankedHelixUpSmall<false, kLeftHalfBankedHelixUpSmallImages>;
        case TrackElemType::RightHalfBankedHelixDownSmall:
            return ClassicWoodenTwisterRCTrackRightHalfBankedHelixDownSmall;

        case TrackElemType::LeftHalfBankedHelixUpLarge:
            return WoodenRCTrackLeftHalfBankedHelixUpLarge<false, kLeftHalfBankedHelixUpLargeImages>;
        case TrackElemType::RightHalfBankedHelixUpLarge:
            return WoodenRCTrackRightHalfBankedHelixUpLarge<false, kRightHalfBankedHelixUpLargeImages>;
        case TrackElemType::LeftHalfBankedHelixDownLarge:
            return ClassicWoodenTwisterRCTrackLeftHalfBankedHelixDownLarge;
        case TrackElemType::RightHalfBankedHelixDownLarge:
            return ClassicWoodenTwisterRCTrackRightHalfBankedHelixDownLarge;

        default:
            return GetTrackPaintFunctionWoodenRC(trackType);
    }
}
