/*****************************************************************************
 * Copyright (c) 2014-2025 OpenRCT2 developers
 *
 * For a complete list of all authors, please refer to contributors.md
 * Interested in contributing? Visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is licensed under the GNU General Public License version 3.
 *****************************************************************************/

#pragma once

#include "../../../SpriteIds.h"
#include "../../../drawing/ImageId.hpp"
#include "../../../paint/Boundbox.h"
#include "../../../paint/track/coaster/LimLaunchedRollerCoasterShared.h"
#include "../../../paint/track/coaster/LoopingRollerCoaster.h"
#include "../../../ride/RideData.h"
#include "../../../world/Location.hpp"

#include <array>

namespace OpenRCT2::LimLaunchedRollerCoaster
{
    // clang-format off
    constexpr std::array<TrackElementSprites, EnumValue(OpenRCT2::TrackElemType::Count)> kSprites = { {
        { &OpenRCT2::LoopingRollerCoaster::kFlatSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kFlatBoundBoxes[0], false }, // Flat
        { &kBlockBrakesSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kStationBoundBoxes[0], false }, // EndStation
        { &kStationSprites[0], nullptr, &OpenRCT2::LoopingRollerCoaster::kStationBoundBoxes[0], false }, // BeginStation
        { &kStationSprites[0], nullptr, &OpenRCT2::LoopingRollerCoaster::kStationBoundBoxes[0], false }, // MiddleStation
        { &OpenRCT2::LoopingRollerCoaster::kUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp25BoundBoxes[0], false }, // Up25
        { &OpenRCT2::LoopingRollerCoaster::kUp60Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp60BoundBoxes[0], false }, // Up60
        { &OpenRCT2::LoopingRollerCoaster::kFlatToUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kFlatToUp25BoundBoxes[0], false }, // FlatToUp25
        { &OpenRCT2::LoopingRollerCoaster::kUp25ToUp60Sprites[0][0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp25ToUp60BoundBoxes[0][0], false }, // Up25ToUp60
        { &OpenRCT2::LoopingRollerCoaster::kUp60ToUp25Sprites[0][0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp60ToUp25BoundBoxes[0][0], false }, // Up60ToUp25
        { &OpenRCT2::LoopingRollerCoaster::kUp25ToFlatSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp25ToFlatBoundBoxes[0], false }, // Up25ToFlat
        { nullptr, nullptr, nullptr, true }, // Down25
        { nullptr, nullptr, nullptr, true }, // Down60
        { nullptr, nullptr, nullptr, true }, // FlatToDown25
        { nullptr, nullptr, nullptr, true }, // Down25ToDown60
        { nullptr, nullptr, nullptr, true }, // Down60ToDown25
        { nullptr, nullptr, nullptr, true }, // Down25ToFlat
        { &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn5TilesSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn5TilesBoundBoxes[0][0], false }, // LeftQuarterTurn5Tiles
        { nullptr, nullptr, nullptr, true }, // RightQuarterTurn5Tiles
        { &OpenRCT2::LoopingRollerCoaster::kFlatToLeftBankSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kFlatToLeftBankBoundBoxes[0][0], false }, // FlatToLeftBank
        { &OpenRCT2::LoopingRollerCoaster::kFlatToRightBankSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kFlatToRightBankBoundBoxes[0][0], false }, // FlatToRightBank
        { nullptr, nullptr, nullptr, true }, // LeftBankToFlat
        { nullptr, nullptr, nullptr, true }, // RightBankToFlat
        { &OpenRCT2::LoopingRollerCoaster::kBankedLeftQuarterTurn5TilesSprites[0][0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kBankedLeftQuarterTurn5TilesBoundBoxes[0][0][0], false }, // BankedLeftQuarterTurn5Tiles
        { nullptr, nullptr, nullptr, true }, // BankedRightQuarterTurn5Tiles
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankToUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftBankToUp25BoundBoxes[0][0], false }, // LeftBankToUp25
        { &OpenRCT2::LoopingRollerCoaster::kRightBankToUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightBankToUp25BoundBoxes[0][0], false }, // RightBankToUp25
        { &OpenRCT2::LoopingRollerCoaster::kUp25ToLeftBankSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp25ToLeftBankBoundBoxes[0][0], false }, // Up25ToLeftBank
        { &OpenRCT2::LoopingRollerCoaster::kUp25ToRightBankSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp25ToRightBankBoundBoxes[0][0], false }, // Up25ToRightBank
        { nullptr, nullptr, nullptr, true }, // LeftBankToDown25
        { nullptr, nullptr, nullptr, true }, // RightBankToDown25
        { nullptr, nullptr, nullptr, true }, // Down25ToLeftBank
        { nullptr, nullptr, nullptr, true }, // Down25ToRightBank
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankSprites[0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftBankBoundBoxes[0], false }, // LeftBank
        { nullptr, nullptr, nullptr, true }, // RightBank
        { &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn5TilesUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn5TilesUp25BoundBoxes[0][0], false }, // LeftQuarterTurn5TilesUp25
        { &OpenRCT2::LoopingRollerCoaster::kRightQuarterTurn5TilesUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightQuarterTurn5TilesUp25BoundBoxes[0][0], false }, // RightQuarterTurn5TilesUp25
        { nullptr, nullptr, nullptr, true }, // LeftQuarterTurn5TilesDown25
        { nullptr, nullptr, nullptr, true }, // RightQuarterTurn5TilesDown25
        { &OpenRCT2::LoopingRollerCoaster::kSBendLeftSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kSBendLeftBoundBoxes[0][0], false }, // SBendLeft
        { &OpenRCT2::LoopingRollerCoaster::kSBendRightSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kSBendRightBoundBoxes[0][0], false }, // SBendRight
        { &kLeftVerticalLoopSprites[0][0], &kLeftVerticalLoopOffsets[0][0], &kLeftVerticalLoopBoundBoxes[0][0], false }, // LeftVerticalLoop
        { &kRightVerticalLoopSprites[0][0], &kRightVerticalLoopOffsets[0][0], &kRightVerticalLoopBoundBoxes[0][0], false }, // RightVerticalLoop
        { &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn3TilesSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn3TilesBoundBoxes[0][0], false }, // LeftQuarterTurn3Tiles
        { nullptr, nullptr, nullptr, true }, // RightQuarterTurn3Tiles
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankedQuarterTurn3TilesSprites[0][0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftBankedQuarterTurn3TilesBoundBoxes[0][0][0], false }, // LeftBankedQuarterTurn3Tiles
        { nullptr, nullptr, nullptr, true }, // RightBankedQuarterTurn3Tiles
        { &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn3TilesUp25Sprites[0][0], &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn3TilesUp25Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn3TilesUp25BoundBoxes[0][0], false }, // LeftQuarterTurn3TilesUp25
        { &OpenRCT2::LoopingRollerCoaster::kRightQuarterTurn3TilesUp25Sprites[0][0], &OpenRCT2::LoopingRollerCoaster::kRightQuarterTurn3TilesUp25Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kRightQuarterTurn3TilesUp25BoundBoxes[0][0], false }, // RightQuarterTurn3TilesUp25
        { nullptr, nullptr, nullptr, true }, // LeftQuarterTurn3TilesDown25
        { nullptr, nullptr, nullptr, true }, // RightQuarterTurn3TilesDown25
        { nullptr, nullptr, nullptr, false }, // LeftQuarterTurn1Tile
        { nullptr, nullptr, nullptr, true }, // RightQuarterTurn1Tile
        { &kLeftTwistDownToUpSprites[0][0][0], nullptr, &kLeftTwistDownToUpBoundBoxes[0][0][0], false }, // LeftTwistDownToUp
        { &kRightTwistDownToUpSprites[0][0][0], nullptr, &kRightTwistDownToUpBoundBoxes[0][0][0], false }, // RightTwistDownToUp
        { nullptr, nullptr, nullptr, true }, // LeftTwistUpToDown
        { nullptr, nullptr, nullptr, true }, // RightTwistUpToDown
        { &kHalfLoopUpSprites[0][0], &kHalfLoopUpOffsets[0][0], &kHalfLoopUpBoundBoxes[0][0], false }, // HalfLoopUp
        { nullptr, nullptr, nullptr, true }, // HalfLoopDown
        { &kLeftCorkscrewUpSprites[0][0], nullptr, &kLeftCorkscrewUpBoundBoxes[0][0], false }, // LeftCorkscrewUp
        { &kRightCorkscrewUpSprites[0][0], nullptr, &kRightCorkscrewUpBoundBoxes[0][0], false }, // RightCorkscrewUp
        { nullptr, nullptr, nullptr, true }, // LeftCorkscrewDown
        { nullptr, nullptr, nullptr, true }, // RightCorkscrewDown
        { &OpenRCT2::LoopingRollerCoaster::kFlatToUp60Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kFlatToUp60BoundBoxes[0][0], false }, // FlatToUp60
        { &OpenRCT2::LoopingRollerCoaster::kUp60ToFlatSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp60ToFlatBoundBoxes[0][0], false }, // Up60ToFlat
        { nullptr, nullptr, nullptr, true }, // FlatToDown60
        { nullptr, nullptr, nullptr, true }, // Down60ToFlat
        { nullptr, nullptr, nullptr, false }, // TowerBase
        { nullptr, nullptr, nullptr, false }, // TowerSection
        { nullptr, nullptr, nullptr, false }, // FlatCovered
        { nullptr, nullptr, nullptr, false }, // Up25Covered
        { nullptr, nullptr, nullptr, false }, // Up60Covered
        { nullptr, nullptr, nullptr, false }, // FlatToUp25Covered
        { nullptr, nullptr, nullptr, false }, // Up25ToUp60Covered
        { nullptr, nullptr, nullptr, false }, // Up60ToUp25Covered
        { nullptr, nullptr, nullptr, false }, // Up25ToFlatCovered
        { nullptr, nullptr, nullptr, false }, // Down25Covered
        { nullptr, nullptr, nullptr, false }, // Down60Covered
        { nullptr, nullptr, nullptr, false }, // FlatToDown25Covered
        { nullptr, nullptr, nullptr, false }, // Down25ToDown60Covered
        { nullptr, nullptr, nullptr, false }, // Down60ToDown25Covered
        { nullptr, nullptr, nullptr, false }, // Down25ToFlatCovered
        { nullptr, nullptr, nullptr, false }, // LeftQuarterTurn5TilesCovered
        { nullptr, nullptr, nullptr, false }, // RightQuarterTurn5TilesCovered
        { nullptr, nullptr, nullptr, false }, // SBendLeftCovered
        { nullptr, nullptr, nullptr, false }, // SBendRightCovered
        { nullptr, nullptr, nullptr, false }, // LeftQuarterTurn3TilesCovered
        { nullptr, nullptr, nullptr, false }, // RightQuarterTurn3TilesCovered
        { &OpenRCT2::LoopingRollerCoaster::kLeftHalfBankedHelixUpSmallSprites[0][0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftHalfBankedHelixUpSmallBoundBoxes[0][0][0], false }, // LeftHalfBankedHelixUpSmall
        { &OpenRCT2::LoopingRollerCoaster::kRightHalfBankedHelixUpSmallSprites[0][0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightHalfBankedHelixUpSmallBoundBoxes[0][0][0], false }, // RightHalfBankedHelixUpSmall
        { nullptr, nullptr, nullptr, true }, // LeftHalfBankedHelixDownSmall
        { nullptr, nullptr, nullptr, true }, // RightHalfBankedHelixDownSmall
        { &OpenRCT2::LoopingRollerCoaster::kLeftHalfBankedHelixUpLargeSprites[0][0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftHalfBankedHelixUpLargeBoundBoxes[0][0][0], false }, // LeftHalfBankedHelixUpLarge
        { &OpenRCT2::LoopingRollerCoaster::kRightHalfBankedHelixUpLargeSprites[0][0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightHalfBankedHelixUpLargeBoundBoxes[0][0][0], false }, // RightHalfBankedHelixUpLarge
        { nullptr, nullptr, nullptr, true }, // LeftHalfBankedHelixDownLarge
        { nullptr, nullptr, nullptr, true }, // RightHalfBankedHelixDownLarge
        { &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn1TileUp60Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftQuarterTurn1TileUp60BoundBoxes[0][0], false }, // LeftQuarterTurn1TileUp60
        { &OpenRCT2::LoopingRollerCoaster::kRightQuarterTurn1TileUp60Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightQuarterTurn1TileUp60BoundBoxes[0][0], false }, // RightQuarterTurn1TileUp60
        { nullptr, nullptr, nullptr, true }, // LeftQuarterTurn1TileDown60
        { nullptr, nullptr, nullptr, true }, // RightQuarterTurn1TileDown60
        { &kBrakesSprites[0], nullptr, &kBrakesBoundBoxes[0], false }, // Brakes
        { &kBoosterSprites[0][0], nullptr, &kBoosterBoundBoxes[0][0], false }, // Booster
        { nullptr, nullptr, nullptr, false }, // Maze
        { nullptr, nullptr, nullptr, false }, // LeftQuarterBankedHelixLargeUp
        { nullptr, nullptr, nullptr, false }, // RightQuarterBankedHelixLargeUp
        { nullptr, nullptr, nullptr, true }, // LeftQuarterBankedHelixLargeDown
        { nullptr, nullptr, nullptr, true }, // RightQuarterBankedHelixLargeDown
        { nullptr, nullptr, nullptr, false }, // LeftQuarterHelixLargeUp
        { nullptr, nullptr, nullptr, false }, // RightQuarterHelixLargeUp
        { nullptr, nullptr, nullptr, true }, // LeftQuarterHelixLargeDown
        { nullptr, nullptr, nullptr, true }, // RightQuarterHelixLargeDown
        { &OpenRCT2::LoopingRollerCoaster::kUp25LeftBankedSprites[0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp25LeftBankedBoundBoxes[0], false }, // Up25LeftBanked
        { &OpenRCT2::LoopingRollerCoaster::kUp25RightBankedSprites[0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp25RightBankedBoundBoxes[0], false }, // Up25RightBanked
        { nullptr, nullptr, nullptr, false }, // Waterfall
        { nullptr, nullptr, nullptr, false }, // Rapids
        { &OpenRCT2::LoopingRollerCoaster::kFlatSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kStationBoundBoxes[0], false }, // OnRidePhoto
        { nullptr, nullptr, nullptr, true }, // Down25LeftBanked
        { nullptr, nullptr, nullptr, true }, // Down25RightBanked
        { nullptr, nullptr, nullptr, false }, // Watersplash
        { &OpenRCT2::LoopingRollerCoaster::kFlatToUp60LongBaseSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kFlatToUp60LongBaseBoundBoxes[0][0], false }, // FlatToUp60LongBase
        { &OpenRCT2::LoopingRollerCoaster::kUp60ToFlatLongBaseSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp60ToFlatLongBaseBoundBoxes[0][0], false }, // Up60ToFlatLongBase
        { nullptr, nullptr, nullptr, false }, // Whirlpool
        { nullptr, nullptr, nullptr, true }, // Down60ToFlatLongBase
        { nullptr, nullptr, nullptr, true }, // FlatToDown60LongBase
        { nullptr, nullptr, nullptr, false }, // CableLiftHill
        { nullptr, nullptr, nullptr, false }, // ReverseFreefallSlope
        { nullptr, nullptr, nullptr, false }, // ReverseFreefallVertical
        { &kUp90Sprites[0][0], nullptr, &kUp90BoundBoxes[0][0], false }, // Up90
        { nullptr, nullptr, nullptr, true }, // Down90
        { &kUp60ToUp90Sprites[0][0], nullptr, &kUp60ToUp90BoundBoxes[0][0], false }, // Up60ToUp90
        { &kDown90ToDown60Sprites[0], nullptr, &kDown90ToDown60BoundBoxes[0], false }, // Down90ToDown60
        { &kUp90ToUp60Sprites[0], nullptr, &kUp90ToUp60BoundBoxes[0], false }, // Up90ToUp60
        { &kDown60ToDown90Sprites[0][0], nullptr, &kDown60ToDown90BoundBoxes[0][0], false }, // Down60ToDown90
        { nullptr, nullptr, nullptr, false }, // BrakeForDrop
        { &OpenRCT2::LoopingRollerCoaster::kLeftEighthToDiagSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftEighthToDiagBoundBoxes[0][0], false }, // LeftEighthToDiag
        { &OpenRCT2::LoopingRollerCoaster::kRightEighthToDiagSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightEighthToDiagBoundBoxes[0][0], false }, // RightEighthToDiag
        { nullptr, nullptr, nullptr, true }, // LeftEighthToOrthogonal
        { nullptr, nullptr, nullptr, true }, // RightEighthToOrthogonal
        { &OpenRCT2::LoopingRollerCoaster::kLeftEighthBankToDiagSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftEighthBankToDiagBoundBoxes[0][0], false }, // LeftEighthBankToDiag
        { &OpenRCT2::LoopingRollerCoaster::kRightEighthBankToDiagSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightEighthBankToDiagBoundBoxes[0][0], false }, // RightEighthBankToDiag
        { nullptr, nullptr, nullptr, true }, // LeftEighthBankToOrthogonal
        { nullptr, nullptr, nullptr, true }, // RightEighthBankToOrthogonal
        { &OpenRCT2::LoopingRollerCoaster::kDiagFlatSprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatOffsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatBoundBoxes[0][0], false }, // DiagFlat
        { &OpenRCT2::LoopingRollerCoaster::kDiagUp25Sprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25BoundBoxes[0][0], false }, // DiagUp25
        { &OpenRCT2::LoopingRollerCoaster::kDiagUp60Sprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp60Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp60BoundBoxes[0][0], false }, // DiagUp60
        { &OpenRCT2::LoopingRollerCoaster::kDiagFlatToUp25Sprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatToUp25Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatToUp25BoundBoxes[0][0], false }, // DiagFlatToUp25
        { &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToUp60Sprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToUp60Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToUp60BoundBoxes[0][0], false }, // DiagUp25ToUp60
        { &OpenRCT2::LoopingRollerCoaster::kDiagUp60ToUp25Sprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp60ToUp25Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp60ToUp25BoundBoxes[0][0], false }, // DiagUp60ToUp25
        { &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToFlatSprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToFlatOffsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToFlatBoundBoxes[0][0], false }, // DiagUp25ToFlat
        { nullptr, nullptr, nullptr, true }, // DiagDown25
        { nullptr, nullptr, nullptr, true }, // DiagDown60
        { nullptr, nullptr, nullptr, true }, // DiagFlatToDown25
        { nullptr, nullptr, nullptr, true }, // DiagDown25ToDown60
        { nullptr, nullptr, nullptr, true }, // DiagDown60ToDown25
        { nullptr, nullptr, nullptr, true }, // DiagDown25ToFlat
        { &OpenRCT2::LoopingRollerCoaster::kDiagFlatToUp60Sprites[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatToUp60Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatToUp60BoundBoxes[0][0], false }, // DiagFlatToUp60
        { &OpenRCT2::LoopingRollerCoaster::kDiagUp60ToFlatSprites[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp60ToFlatOffsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp60ToFlatBoundBoxes[0][0], false }, // DiagUp60ToFlat
        { nullptr, nullptr, nullptr, true }, // DiagFlatToDown60
        { nullptr, nullptr, nullptr, true }, // DiagDown60ToFlat
        { &OpenRCT2::LoopingRollerCoaster::kDiagFlatToLeftBankSprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatToLeftBankOffsets[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatToLeftBankBoundBoxes[0][0][0], false }, // DiagFlatToLeftBank
        { &OpenRCT2::LoopingRollerCoaster::kDiagFlatToRightBankSprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatToRightBankOffsets[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagFlatToRightBankBoundBoxes[0][0][0], false }, // DiagFlatToRightBank
        { nullptr, nullptr, nullptr, true }, // DiagLeftBankToFlat
        { nullptr, nullptr, nullptr, true }, // DiagRightBankToFlat
        { &OpenRCT2::LoopingRollerCoaster::kDiagLeftBankToUp25Sprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagLeftBankToUp25Offsets[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagLeftBankToUp25BoundBoxes[0][0][0], false }, // DiagLeftBankToUp25
        { &OpenRCT2::LoopingRollerCoaster::kDiagRightBankToUp25Sprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagRightBankToUp25Offsets[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagRightBankToUp25BoundBoxes[0][0][0], false }, // DiagRightBankToUp25
        { &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToLeftBankSprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToLeftBankOffsets[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToLeftBankBoundBoxes[0][0][0], false }, // DiagUp25ToLeftBank
        { &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToRightBankSprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToRightBankOffsets[0][0][0], &OpenRCT2::LoopingRollerCoaster::kDiagUp25ToRightBankBoundBoxes[0][0][0], false }, // DiagUp25ToRightBank
        { nullptr, nullptr, nullptr, true }, // DiagLeftBankToDown25
        { nullptr, nullptr, nullptr, true }, // DiagRightBankToDown25
        { nullptr, nullptr, nullptr, true }, // DiagDown25ToLeftBank
        { nullptr, nullptr, nullptr, true }, // DiagDown25ToRightBank
        { &OpenRCT2::LoopingRollerCoaster::kDiagLeftBankSprites[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagLeftBankOffsets[0][0], &OpenRCT2::LoopingRollerCoaster::kDiagLeftBankBoundBoxes[0][0], false }, // DiagLeftBank
        { nullptr, nullptr, nullptr, true }, // DiagRightBank
        { nullptr, nullptr, nullptr, false }, // LogFlumeReverser
        { nullptr, nullptr, nullptr, false }, // SpinningTunnel
        { &kLeftBarrelRollUpToDownSprites[0][0][0], nullptr, &kLeftBarrelRollUpToDownBoundBoxes[0][0][0], false }, // LeftBarrelRollUpToDown
        { &kRightBarrelRollUpToDownSprites[0][0][0], nullptr, &kRightBarrelRollUpToDownBoundBoxes[0][0][0], false }, // RightBarrelRollUpToDown
        { nullptr, nullptr, nullptr, true }, // LeftBarrelRollDownToUp
        { nullptr, nullptr, nullptr, true }, // RightBarrelRollDownToUp
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankToLeftQuarterTurn3TilesUp25Sprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kLeftBankToLeftQuarterTurn3TilesUp25Offsets[0][0][0], &OpenRCT2::LoopingRollerCoaster::kLeftBankToLeftQuarterTurn3TilesUp25BoundBoxes[0][0][0], false }, // LeftBankToLeftQuarterTurn3TilesUp25
        { &OpenRCT2::LoopingRollerCoaster::kRightBankToRightQuarterTurn3TilesUp25Sprites[0][0][0], &OpenRCT2::LoopingRollerCoaster::kRightBankToRightQuarterTurn3TilesUp25Offsets[0][0][0], &OpenRCT2::LoopingRollerCoaster::kRightBankToRightQuarterTurn3TilesUp25BoundBoxes[0][0][0], false }, // RightBankToRightQuarterTurn3TilesUp25
        { nullptr, nullptr, nullptr, true }, // LeftQuarterTurn3TilesDown25ToLeftBank
        { nullptr, nullptr, nullptr, true }, // RightQuarterTurn3TilesDown25ToRightBank
        { nullptr, nullptr, nullptr, false }, // PoweredLift
        { &kLeftLargeHalfLoopUpSprites[0][0], nullptr, &kLeftLargeHalfLoopUpBoundBoxes[0][0], false }, // LeftLargeHalfLoopUp
        { &kRightLargeHalfLoopUpSprites[0][0], nullptr, &kRightLargeHalfLoopUpBoundBoxes[0][0], false }, // RightLargeHalfLoopUp
        { nullptr, nullptr, nullptr, true }, // LeftLargeHalfLoopDown
        { nullptr, nullptr, nullptr, true }, // RightLargeHalfLoopDown
        { nullptr, nullptr, nullptr, false }, // LeftFlyerTwistUp
        { nullptr, nullptr, nullptr, false }, // RightFlyerTwistUp
        { nullptr, nullptr, nullptr, false }, // LeftFlyerTwistDown
        { nullptr, nullptr, nullptr, false }, // RightFlyerTwistDown
        { nullptr, nullptr, nullptr, false }, // FlyerHalfLoopUninvertedUp
        { nullptr, nullptr, nullptr, false }, // FlyerHalfLoopInvertedDown
        { nullptr, nullptr, nullptr, false }, // LeftFlyerCorkscrewUp
        { nullptr, nullptr, nullptr, false }, // RightFlyerCorkscrewUp
        { nullptr, nullptr, nullptr, false }, // LeftFlyerCorkscrewDown
        { nullptr, nullptr, nullptr, false }, // RightFlyerCorkscrewDown
        { nullptr, nullptr, nullptr, false }, // HeartLineTransferUp
        { nullptr, nullptr, nullptr, true }, // HeartLineTransferDown
        { nullptr, nullptr, nullptr, false }, // LeftHeartLineRoll
        { nullptr, nullptr, nullptr, false }, // RightHeartLineRoll
        { nullptr, nullptr, nullptr, false }, // MinigolfHoleA
        { nullptr, nullptr, nullptr, false }, // MinigolfHoleB
        { nullptr, nullptr, nullptr, false }, // MinigolfHoleC
        { nullptr, nullptr, nullptr, false }, // MinigolfHoleD
        { nullptr, nullptr, nullptr, false }, // MinigolfHoleE
        { nullptr, nullptr, nullptr, false }, // MultiDimInvertedFlatToDown90QuarterLoop
        { &kUp90ToInvertedFlatQuarterLoopSprites[0][0], nullptr, &kUp90ToInvertedFlatQuarterLoopBoundBoxes[0][0], false }, // Up90ToInvertedFlatQuarterLoop
        { &kInvertedFlatToDown90QuarterLoopSprites[0][0], nullptr, &kInvertedFlatToDown90QuarterLoopBoundBoxes[0][0], false }, // InvertedFlatToDown90QuarterLoop
        { nullptr, nullptr, nullptr, false }, // LeftCurvedLiftHill
        { nullptr, nullptr, nullptr, false }, // RightCurvedLiftHill
        { nullptr, nullptr, nullptr, false }, // LeftReverser
        { nullptr, nullptr, nullptr, true }, // RightReverser
        { nullptr, nullptr, nullptr, false }, // AirThrustTopCap
        { nullptr, nullptr, nullptr, true }, // AirThrustVerticalDown
        { nullptr, nullptr, nullptr, true }, // AirThrustVerticalDownToLevel
        { &kBlockBrakesSprites[0][0], nullptr, &kBlockBrakesBoundBoxes[0], false }, // BlockBrakes
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankedQuarterTurn3TileUp25Sprites[0][0], &OpenRCT2::LoopingRollerCoaster::kLeftBankedQuarterTurn3TileUp25Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kLeftBankedQuarterTurn3TileUp25BoundBoxes[0][0], false }, // LeftBankedQuarterTurn3TileUp25
        { &OpenRCT2::LoopingRollerCoaster::kRightBankedQuarterTurn3TileUp25Sprites[0][0], &OpenRCT2::LoopingRollerCoaster::kRightBankedQuarterTurn3TileUp25Offsets[0][0], &OpenRCT2::LoopingRollerCoaster::kRightBankedQuarterTurn3TileUp25BoundBoxes[0][0], false }, // RightBankedQuarterTurn3TileUp25
        { nullptr, nullptr, nullptr, true }, // LeftBankedQuarterTurn3TileDown25
        { nullptr, nullptr, nullptr, true }, // RightBankedQuarterTurn3TileDown25
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankedQuarterTurn5TileUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftBankedQuarterTurn5TileUp25BoundBoxes[0][0], false }, // LeftBankedQuarterTurn5TileUp25
        { &OpenRCT2::LoopingRollerCoaster::kRightBankedQuarterTurn5TileUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightBankedQuarterTurn5TileUp25BoundBoxes[0][0], false }, // RightBankedQuarterTurn5TileUp25
        { nullptr, nullptr, nullptr, true }, // LeftBankedQuarterTurn5TileDown25
        { nullptr, nullptr, nullptr, true }, // RightBankedQuarterTurn5TileDown25
        { &OpenRCT2::LoopingRollerCoaster::kUp25ToLeftBankedUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp25ToLeftBankedUp25BoundBoxes[0][0], false }, // Up25ToLeftBankedUp25
        { &OpenRCT2::LoopingRollerCoaster::kUp25ToRightBankedUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kUp25ToRightBankedUp25BoundBoxes[0][0], false }, // Up25ToRightBankedUp25
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankedUp25ToUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftBankedUp25ToUp25BoundBoxes[0][0], false }, // LeftBankedUp25ToUp25
        { &OpenRCT2::LoopingRollerCoaster::kRightBankedUp25ToUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightBankedUp25ToUp25BoundBoxes[0][0], false }, // RightBankedUp25ToUp25
        { nullptr, nullptr, nullptr, true }, // Down25ToLeftBankedDown25
        { nullptr, nullptr, nullptr, true }, // Down25ToRightBankedDown25
        { nullptr, nullptr, nullptr, true }, // LeftBankedDown25ToDown25
        { nullptr, nullptr, nullptr, true }, // RightBankedDown25ToDown25
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankedFlatToLeftBankedUp25Sprites[0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftBankedFlatToLeftBankedUp25BoundBoxes[0], false }, // LeftBankedFlatToLeftBankedUp25
        { &OpenRCT2::LoopingRollerCoaster::kRightBankedFlatToRightBankedUp25Sprites[0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightBankedFlatToRightBankedUp25BoundBoxes[0], false }, // RightBankedFlatToRightBankedUp25
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankedUp25ToLeftBankedFlatSprites[0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftBankedUp25ToLeftBankedFlatBoundBoxes[0], false }, // LeftBankedUp25ToLeftBankedFlat
        { &OpenRCT2::LoopingRollerCoaster::kRightBankedUp25ToRightBankedFlatSprites[0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightBankedUp25ToRightBankedFlatBoundBoxes[0], false }, // RightBankedUp25ToRightBankedFlat
        { nullptr, nullptr, nullptr, true }, // LeftBankedFlatToLeftBankedDown25
        { nullptr, nullptr, nullptr, true }, // RightBankedFlatToRightBankedDown25
        { nullptr, nullptr, nullptr, true }, // LeftBankedDown25ToLeftBankedFlat
        { nullptr, nullptr, nullptr, true }, // RightBankedDown25ToRightBankedFlat
        { &OpenRCT2::LoopingRollerCoaster::kFlatToLeftBankedUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kFlatToLeftBankedUp25BoundBoxes[0][0], false }, // FlatToLeftBankedUp25
        { &OpenRCT2::LoopingRollerCoaster::kFlatToRightBankedUp25Sprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kFlatToRightBankedUp25BoundBoxes[0][0], false }, // FlatToRightBankedUp25
        { &OpenRCT2::LoopingRollerCoaster::kLeftBankedUp25ToFlatSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kLeftBankedUp25ToFlatBoundBoxes[0][0], false }, // LeftBankedUp25ToFlat
        { &OpenRCT2::LoopingRollerCoaster::kRightBankedUp25ToFlatSprites[0][0], nullptr, &OpenRCT2::LoopingRollerCoaster::kRightBankedUp25ToFlatBoundBoxes[0][0], false }, // RightBankedUp25ToFlat
        { nullptr, nullptr, nullptr, true }, // FlatToLeftBankedDown25
        { nullptr, nullptr, nullptr, true }, // FlatToRightBankedDown25
        { nullptr, nullptr, nullptr, true }, // LeftBankedDown25ToFlat
        { nullptr, nullptr, nullptr, true }, // RightBankedDown25ToFlat
        { &kLeftQuarterTurn1TileUp90Sprites[0][0][0], nullptr, &kLeftQuarterTurn1TileUp90BoundBoxes[0][0][0], false }, // LeftQuarterTurn1TileUp90
        { &kRightQuarterTurn1TileUp90Sprites[0][0][0], nullptr, &kRightQuarterTurn1TileUp90BoundBoxes[0][0][0], false }, // RightQuarterTurn1TileUp90
        { nullptr, nullptr, nullptr, true }, // LeftQuarterTurn1TileDown90
        { nullptr, nullptr, nullptr, true }, // RightQuarterTurn1TileDown90
        { nullptr, nullptr, nullptr, false }, // MultiDimUp90ToInvertedFlatQuarterLoop
        { nullptr, nullptr, nullptr, false }, // MultiDimFlatToDown90QuarterLoop
        { nullptr, nullptr, nullptr, false }, // MultiDimInvertedUp90ToFlatQuarterLoop
        { nullptr, nullptr, nullptr, false }, // RotationControlToggle
        { nullptr, nullptr, nullptr, false }, // FlatTrack1x4A
        { nullptr, nullptr, nullptr, false }, // FlatTrack2x2
        { nullptr, nullptr, nullptr, false }, // FlatTrack4x4
        { nullptr, nullptr, nullptr, false }, // FlatTrack2x4
        { nullptr, nullptr, nullptr, false }, // FlatTrack1x5
        { nullptr, nullptr, nullptr, false }, // FlatTrack1x1A
        { nullptr, nullptr, nullptr, false }, // FlatTrack1x4B
        { nullptr, nullptr, nullptr, false }, // FlatTrack1x1B
        { nullptr, nullptr, nullptr, false }, // FlatTrack1x4C
        { nullptr, nullptr, nullptr, false }, // FlatTrack3x3
        { &kLeftLargeCorkscrewUpSprites[0][0], nullptr, &kLeftLargeCorkscrewUpBoundBoxes[0][0], false }, // LeftLargeCorkscrewUp
        { &kRightLargeCorkscrewUpSprites[0][0], nullptr, &kRightLargeCorkscrewUpBoundBoxes[0][0], false }, // RightLargeCorkscrewUp
        { nullptr, nullptr, nullptr, true }, // LeftLargeCorkscrewDown
        { nullptr, nullptr, nullptr, true }, // RightLargeCorkscrewDown
        { &kLeftMediumHalfLoopUpSprites[0][0], nullptr, &kLeftMediumHalfLoopUpBoundBoxes[0][0], false }, // LeftMediumHalfLoopUp
        { &kRightMediumHalfLoopUpSprites[0][0], nullptr, &kRightMediumHalfLoopUpBoundBoxes[0][0], false }, // RightMediumHalfLoopUp
        { nullptr, nullptr, nullptr, true }, // LeftMediumHalfLoopDown
        { nullptr, nullptr, nullptr, true }, // RightMediumHalfLoopDown
        { &kLeftZeroGRollUpSprites[0][0][0], nullptr, &kLeftZeroGRollUpBoundBoxes[0][0][0], false }, // LeftZeroGRollUp
        { &kRightZeroGRollUpSprites[0][0][0], nullptr, &kRightZeroGRollUpBoundBoxes[0][0][0], false }, // RightZeroGRollUp
        { nullptr, nullptr, nullptr, true }, // LeftZeroGRollDown
        { nullptr, nullptr, nullptr, true }, // RightZeroGRollDown
        { &kLeftLargeZeroGRollUpSprites[0][0][0], nullptr, &kLeftLargeZeroGRollUpBoundBoxes[0][0][0], false }, // LeftLargeZeroGRollUp
        { &kRightLargeZeroGRollUpSprites[0][0][0], nullptr, &kRightLargeZeroGRollUpBoundBoxes[0][0][0], false }, // RightLargeZeroGRollUp
        { nullptr, nullptr, nullptr, true }, // LeftLargeZeroGRollDown
        { nullptr, nullptr, nullptr, true }, // RightLargeZeroGRollDown
        { nullptr, nullptr, nullptr, false }, // LeftFlyerLargeHalfLoopUninvertedUp
        { nullptr, nullptr, nullptr, false }, // RightFlyerLargeHalfLoopUninvertedUp
        { nullptr, nullptr, nullptr, false }, // LeftFlyerLargeHalfLoopInvertedDown
        { nullptr, nullptr, nullptr, false }, // RightFlyerLargeHalfLoopInvertedDown
        { nullptr, nullptr, nullptr, false }, // LeftFlyerLargeHalfLoopInvertedUp
        { nullptr, nullptr, nullptr, false }, // RightFlyerLargeHalfLoopInvertedUp
        { nullptr, nullptr, nullptr, false }, // LeftFlyerLargeHalfLoopUninvertedDown
        { nullptr, nullptr, nullptr, false }, // RightFlyerLargeHalfLoopUninvertedDown
        { nullptr, nullptr, nullptr, false }, // FlyerHalfLoopInvertedUp
        { nullptr, nullptr, nullptr, false }, // FlyerHalfLoopUninvertedDown
        { nullptr, nullptr, nullptr, false }, // LeftEighthToDiagUp25
        { nullptr, nullptr, nullptr, false }, // RightEighthToDiagUp25
        { nullptr, nullptr, nullptr, true }, // LeftEighthToDiagDown25
        { nullptr, nullptr, nullptr, true }, // RightEighthToDiagDown25
        { nullptr, nullptr, nullptr, false }, // LeftEighthToOrthogonalUp25
        { nullptr, nullptr, nullptr, false }, // RightEighthToOrthogonalUp25
        { nullptr, nullptr, nullptr, true }, // LeftEighthToOrthogonalDown25
        { nullptr, nullptr, nullptr, true }, // RightEighthToOrthogonalDown25
        { nullptr, nullptr, nullptr, false }, // DiagUp25ToLeftBankedUp25
        { nullptr, nullptr, nullptr, false }, // DiagUp25ToRightBankedUp25
        { nullptr, nullptr, nullptr, false }, // DiagLeftBankedUp25ToUp25
        { nullptr, nullptr, nullptr, false }, // DiagRightBankedUp25ToUp25
        { nullptr, nullptr, nullptr, true }, // DiagDown25ToLeftBankedDown25
        { nullptr, nullptr, nullptr, true }, // DiagDown25ToRightBankedDown25
        { nullptr, nullptr, nullptr, true }, // DiagLeftBankedDown25ToDown25
        { nullptr, nullptr, nullptr, true }, // DiagRightBankedDown25ToDown25
        { nullptr, nullptr, nullptr, false }, // DiagLeftBankedFlatToLeftBankedUp25
        { nullptr, nullptr, nullptr, false }, // DiagRightBankedFlatToRightBankedUp25
        { nullptr, nullptr, nullptr, false }, // DiagLeftBankedUp25ToLeftBankedFlat
        { nullptr, nullptr, nullptr, false }, // DiagRightBankedUp25ToRightBankedFlat
        { nullptr, nullptr, nullptr, true }, // DiagLeftBankedFlatToLeftBankedDown25
        { nullptr, nullptr, nullptr, true }, // DiagRightBankedFlatToRightBankedDown25
        { nullptr, nullptr, nullptr, true }, // DiagLeftBankedDown25ToLeftBankedFlat
        { nullptr, nullptr, nullptr, true }, // DiagRightBankedDown25ToRightBankedFlat
        { nullptr, nullptr, nullptr, false }, // DiagFlatToLeftBankedUp25
        { nullptr, nullptr, nullptr, false }, // DiagFlatToRightBankedUp25
        { nullptr, nullptr, nullptr, false }, // DiagLeftBankedUp25ToFlat
        { nullptr, nullptr, nullptr, false }, // DiagRightBankedUp25ToFlat
        { nullptr, nullptr, nullptr, true }, // DiagFlatToLeftBankedDown25
        { nullptr, nullptr, nullptr, true }, // DiagFlatToRightBankedDown25
        { nullptr, nullptr, nullptr, true }, // DiagLeftBankedDown25ToFlat
        { nullptr, nullptr, nullptr, true }, // DiagRightBankedDown25ToFlat
        { nullptr, nullptr, nullptr, false }, // DiagUp25LeftBanked
        { nullptr, nullptr, nullptr, false }, // DiagUp25RightBanked
        { nullptr, nullptr, nullptr, true }, // DiagDown25LeftBanked
        { nullptr, nullptr, nullptr, true }, // DiagDown25RightBanked
        { nullptr, nullptr, nullptr, false }, // LeftEighthBankToDiagUp25
        { nullptr, nullptr, nullptr, false }, // RightEighthBankToDiagUp25
        { nullptr, nullptr, nullptr, true }, // LeftEighthBankToDiagDown25
        { nullptr, nullptr, nullptr, true }, // RightEighthBankToDiagDown25
        { nullptr, nullptr, nullptr, false }, // LeftEighthBankToOrthogonalUp25
        { nullptr, nullptr, nullptr, false }, // RightEighthBankToOrthogonalUp25
        { nullptr, nullptr, nullptr, true }, // LeftEighthBankToOrthogonalDown25
        { nullptr, nullptr, nullptr, true }, // RightEighthBankToOrthogonalDown25
        { nullptr, nullptr, nullptr, false }, // DiagBrakes
        { nullptr, nullptr, nullptr, false }, // DiagBlockBrakes
        { nullptr, nullptr, nullptr, false }, // Down25Brakes
        { nullptr, nullptr, nullptr, false }, // DiagBooster
        { nullptr, nullptr, nullptr, false }, // DiagFlatToUp60LongBase
        { nullptr, nullptr, nullptr, false }, // DiagUp60ToFlatLongBase
        { nullptr, nullptr, nullptr, true }, // DiagFlatToDown60LongBase
        { nullptr, nullptr, nullptr, true }, // DiagDown60ToFlatLongBase
        { nullptr, nullptr, nullptr, false }, // LeftEighthDiveLoopUpToOrthogonal
        { nullptr, nullptr, nullptr, false }, // RightEighthDiveLoopUpToOrthogonal
        { nullptr, nullptr, nullptr, true }, // LeftEighthDiveLoopDownToDiag
        { nullptr, nullptr, nullptr, true }, // RightEighthDiveLoopDownToDiag
        { nullptr, nullptr, nullptr, false }, // DiagDown25Brakes
    } };
    // clang-format on
} // namespace OpenRCT2::LimLaunchedRollerCoaster
