namespace OpenRCT2.Unity
{
    public enum PeepSpriteType : byte
    {
        Normal = 0,
        Handyman = 1,
        Mechanic = 2,
        Security = 3,
        EntertainerPanda = 4,
        EntertainerTiger = 5,
        EntertainerElephant = 6,
        EntertainerRoman = 7,
        EntertainerGorilla = 8,
        EntertainerSnowman = 9,
        EntertainerKnight = 10,
        EntertainerAstronaut = 11,
        EntertainerBandit = 12,
        EntertainerSheriff = 13,
        EntertainerPirate = 14,
        IceCream = 15,
        Chips = 16,
        Burger = 17,
        Drink = 18,
        Balloon = 19,
        Candyfloss = 20,
        Umbrella = 21,
        Pizza = 22,
        SecurityAlternate = 23,
        Popcorn = 24,
        ArmsCrossed = 25,
        HeadDown = 26,
        Nauseous = 27,
        VeryNauseous = 28,
        RequireBathroom = 29,
        Hat = 30,
        HotDog = 31,
        Tentacle = 32,
        ToffeeApple = 33,
        Doughnut = 34,
        Coffee = 35,
        Chicken = 36,
        Lemonade = 37,
        Watching = 38,
        Pretzel = 39,
        Sunglasses = 40,
        SuJongkwa = 41,
        Juice = 42,
        Funnel_cake = 43,
        Noodles = 44,
        Sausage = 45,
        Soup = 46,
        Sandwich = 47,

        Invalid = 255
    };
}
