#pragma region Copyright (c) 2014-2016 OpenRCT2 Developers
/*****************************************************************************
 * OpenRCT2, an open source clone of Roller Coaster Tycoon 2.
 *
 * OpenRCT2 is the work of many authors, a full list can be found in contributors.md
 * For more information, visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * A full copy of the GNU General Public License can be found in licence.txt
 *****************************************************************************/
#pragma endregion

#include "../src/common.h"

const utf8string RideNames[91] = {
	"Spiral Roller Coaster",
	"Stand-up Roller Coaster",
	"Suspended Swinging Coaster",
	"Inverted Roller Coaster",
	"Junior Roller Coaster",
	"Miniature Railway",
	"Monorail",
	"Mini Suspended Coaster",
	"Boat Ride",
	"Wooden Wild Mouse",
	"Steeplechase",
	"Car Ride",
	"Launched Freefall",
	"Bobsleigh Coaster",
	"Observation Tower",
	"Looping Roller Coaster",
	"Dinghy Slide",
	"Mine Train Coaster",
	"Chairlift",
	"Corkscrew Roller Coaster",
	"Maze",
	"Spiral Slide",
	"Go Karts",
	"Log Flume",
	"River Rapids",
	"Dodgems",
	"Pirate Ship",
	"Swinging Inverter Ship",
	"Food Stall",
	"Unknown Stall",
	"Drink Stall",
	"Unknown Stall",
	"Shop",
	"Merry-Go-Round",
	"Unknown Stall",
	"Information Kiosk",
	"Toilets",
	"Ferris Wheel",
	"Motion Simulator",
	"3D Cinema",
	"Top Spin",
	"Space Rings",
	"Reverse Freefall Coaster",
	"Lift",
	"Vertical Drop Roller Coaster",
	"Cash Machine",
	"Twist",
	"Haunted House",
	"First Aid Room",
	"Circus Show",
	"Ghost Train",
	"Steel Twister Roller Coaster",
	"Wooden Roller Coaster",
	"Side-Friction Roller Coaster",
	"Wild Mouse",
	"Multi-Dimension Roller Coaster",
	"Unknown Ride",
	"Flying Roller Coaster",
	"Unknown Ride",
	"Virginia Reel",
	"Splash Boats",
	"Mini Helicopters",
	"Lay-down Roller Coaster",
	"Suspended Monorail",
	"Unknown Ride",
	"Reverser Roller Coaster",
	"Heartline Twister Coaster",
	"Mini Golf",
	"Giga Coaster",
	"Roto-Drop",
	"Flying Saucers",
	"Crooked House",
	"Monorail Cycles",
	"Compact Inverted Coaster",
	"Water Coaster",
	"Air Powered Vertical Coaster",
	"Inverted Hairpin Coaster",
	"Magic Carpet",
	"Submarine Ride",
	"River Rafts",
	"Unknown Ride",
	"Enterprise",
	"Unknown Ride",
	"Unknown Ride",
	"Unknown Ride",
	"Unknown Ride",
	"Inverted Impulse Coaster",
	"Mini Roller Coaster",
	"Mine Ride",
	"Unknown Ride",
	"LIM Launched Roller Coaster",
};

const utf8string TrackNames[256] = {
	"Flat",
	"End Station",
	"Begin Station",
	"Middle Station",
	"25 Deg Up",
	"60 Deg Up",
	"Flat to 25 deg Up",
	"25 Deg up to 60 deg Up",
	"60 Deg up to 25 deg Up",
	"25 Deg up to Flat",
	"25 Deg Down",
	"60 Deg Down",
	"Flat to 25 deg Down",
	"25 Deg Down to 60 deg Down",
	"60 Deg Down to 25 deg Down",
	"25 Deg Down to Flat",
	"Left Quarter Turn 5 Tiles",
	"Right Quarter Turn 5 Tiles",
	"Flat to Left Bank",
	"Flat to Right Bank",
	"Left Bank to Flat",
	"Right Bank to Flat",
	"Banked Left Quarter Turn 5 Tiles",
	"Banked Right Quarter Turn 5 Tiles",
	"Left Bank to 25 deg Up",
	"Right Bank to 25 deg Up",
	"25 Deg up to Left Bank",
	"25 Deg up to Right Bank",
	"Left Bank to 25 deg Down",
	"Right Bank to 25 deg Down",
	"25 Deg Down to Left Bank",
	"25 Deg Down to Right Bank",
	"Left Bank",
	"Right Bank",
	"Left Quarter Turn 5 Tiles 25 deg Up",
	"Right Quarter Turn 5 Tiles 25 deg Up",
	"Left Quarter Turn 5 Tiles 25 deg Down",
	"Right Quarter Turn 5 Tiles 25 deg Down",
	"S Bend Left",
	"S Bend Right",
	"Left Vertical Loop",
	"Right Vertical Loop",
	"Left Quarter Turn 3 Tiles",
	"Right Quarter Turn 3 Tiles",
	"Left Quarter Turn 3 Tiles Bank",
	"Right Quarter Turn 3 Tiles Bank",
	"Left Quarter Turn 3 Tiles 25 deg Up",
	"Right Quarter Turn 3 Tiles 25 deg Up",
	"Left Quarter Turn 3 Tiles 25 deg Down",
	"Right Quarter Turn 3 Tiles 25 deg Down",
	"Left Quarter Turn 1 Tile",
	"Right Quarter Turn 1 Tile",
	"Left Twist Down to Up",
	"Right Twist Down to Up",
	"Left Twist up to Down",
	"Right Twist up to Down",
	"Half Loop Up",
	"Half Loop Down",
	"Left Corkscrew Up",
	"Right Corkscrew Up",
	"Left Corkscrew Down",
	"Right Corkscrew Down",
	"Flat to 60 deg Up",
	"60 Deg up to Flat",
	"Flat to 60 deg Down",
	"60 Deg Down to Flat",
	"Tower Base",
	"Tower Section",
	"Flat Covered",
	"25 Deg up Covered",
	"60 Deg up Covered",
	"Flat to 25 deg up Covered",
	"25 Deg up to 60 deg up Covered",
	"60 Deg up to 25 deg up Covered",
	"25 Deg up to Flat Covered",
	"25 Deg Down Covered",
	"60 Deg Down Covered",
	"Flat to 25 deg Down Covered",
	"25 Deg Down to 60 deg Down Covered",
	"60 Deg Down to 25 deg Down Covered",
	"25 Deg Down to Flat Covered",
	"Left Quarter Turn 5 Tiles Covered",
	"Right Quarter Turn 5 Tiles Covered",
	"S Bend Left Covered",
	"S Bend Right Covered",
	"Left Quarter Turn 3 Tiles Covered",
	"Right Quarter Turn 3 Tiles Covered",
	"Left Half Banked Helix up Small",
	"Right Half Banked Helix up Small",
	"Left Half Banked Helix Down Small",
	"Right Half Banked Helix Down Small",
	"Left Half Banked Helix up Large",
	"Right Half Banked Helix up Large",
	"Left Half Banked Helix Down Large",
	"Right Half Banked Helix Down Large",
	"Left Quarter Turn 1 Tile 60 deg Up",
	"Right Quarter Turn 1 Tile 60 deg Up",
	"Left Quarter Turn 1 Tile 60 deg Down",
	"Right Quarter Turn 1 Tile 60 deg Down",
	"Brakes",
	"Rotation Control Toggle",
	"Inverted 90 deg up to Flat Quarter Loop/Maze",
	"Left Quarter Banked Helix Large Up",
	"Right Quarter Banked Helix Large Up",
	"Left Quarter Banked Helix Large Down",
	"Right Quarter Banked Helix Large Down",
	"Left Quarter Helix Large Up",
	"Right Quarter Helix Large Up",
	"Left Quarter Helix Large Down",
	"Right Quarter Helix Large Down",
	"25 Deg up Left Banked",
	"25 Deg up Right Banked",
	"Waterfall",
	"Rapids",
	"On Ride Photo",
	"25 Deg Down Left Banked",
	"25 Deg Down Right Banked",
	"Water Splash",
	"Flat to 60 deg up Long Base",
	"60 Deg up to Flat Long Base",
	"Whirlpool",
	"Flat to 60 deg Down Long Base",
	"60 Deg up to Flat Long Base 122",
	"Cable Lift Hill",
	"Reverse Whoa Belly Slope",
	"Reverse Whoa Belly Vertical",
	"90 Deg Up",
	"90 Deg Down",
	"60 Deg up to 90 deg Up",
	"90 Deg Down to 60 deg Down",
	"90 Deg up to 60 deg Up",
	"60 Deg Down to 90 deg Down",
	"Brake for Drop",
	"Left Eighth to Diag",
	"Right Eighth to Diag",
	"Left Eighth to Orthogonal",
	"Right Eighth to Orthogonal",
	"Left Eighth Bank to Diag",
	"Right Eighth Bank to Diag",
	"Left Eighth Bank to Orthogonal",
	"Right Eighth Bank to Orthogonal",
	"Diag Flat",
	"Diag 25 deg Up",
	"Diag 60 deg Up",
	"Diag Flat to 25 deg Up",
	"Diag 25 deg up to 60 deg Up",
	"Diag 60 deg up to 25 deg Up",
	"Diag 25 deg up to Flat",
	"Diag 25 deg Down",
	"Diag 60 deg Down",
	"Diag Flat to 25 deg Down",
	"Diag 25 deg Down to 60 deg Down",
	"Diag 60 deg Down to 25 deg Down",
	"Diag 25 deg Down to Flat",
	"Diag Flat to 60 deg Up",
	"Diag 60 deg up to Flat",
	"Diag Flat to 60 deg Down",
	"Diag 60 deg Down to Flat",
	"Diag Flat to Left Bank",
	"Diag Flat to Right Bank",
	"Diag Left Bank to Flat",
	"Diag Right Bank to Flat",
	"Diag Left Bank to 25 deg Up",
	"Diag Right Bank to 25 deg Up",
	"Diag 25 deg up to Left Bank",
	"Diag 25 deg up to Right Bank",
	"Diag Left Bank to 25 deg Down",
	"Diag Right Bank to 25 deg Down",
	"Diag 25 deg Down to Left Bank",
	"Diag 25 deg Down to Right Bank",
	"Diag Left Bank",
	"Diag Right Bank",
	"Log Flume Reverser",
	"Spinning Tunnel",
	"Left Barrel Roll up to Down",
	"Right Barrel Roll up to Down",
	"Left Barrel Roll Down to Up",
	"Right Barrel Roll Down to Up",
	"Left Bank to Left Quarter Turn 3 Tiles 25 deg Up",
	"Right Bank to Right Quarter Turn 3 Tiles 25 deg Up",
	"Left Quarter Turn 3 Tiles 25 deg Down to Left Bank",
	"Right Quarter Turn 3 Tiles 25 deg Down to Right Bank",
	"Powered Lift",
	"Left Large Half Loop Up",
	"Right Large Half Loop Up",
	"Right Large Half Loop Down",
	"Left Large Half Loop Down",
	"Left Flyer Twist Up",
	"Right Flyer Twist Up",
	"Left Flyer Twist Down",
	"Right Flyer Twist Down",
	"Flyer Half Loop Up",
	"Flyer Half Loop Down",
	"Left Flyer Corkscrew Up",
	"Right Flyer Corkscrew Up",
	"Left Flyer Corkscrew Down",
	"Right Flyer Corkscrew Down",
	"Heartline Transfer Up",
	"Heartline Transfer Down",
	"Left Heartline Roll",
	"Right Heartline Roll",
	"Mini Golf Hole A",
	"Mini Golf Hole B",
	"Mini Golf Hole C",
	"Mini Golf Hole D",
	"Mini Golf Hole E",
	"Multidim Inverted Flat to 90 deg Quarter Loop Down",
	"90 Deg to Inverted Flat Quarter Loop Up",
	"Inverted Flat to 90 deg Quarter Loop Down",
	"Left Curved Lift Hill",
	"Right Curved Lift Hill",
	"Left Reverser",
	"Right Reverser",
	"Air Thrust top Cap",
	"Air Thrust Vertical Down",
	"Air Thrust Vertical Down to Level",
	"Block Brakes",
	"Left Banked Quarter Turn 3 Tile 25 deg Up",
	"Right Banked Quarter Turn 3 Tile 25 deg Up",
	"Left Banked Quarter Turn 3 Tile 25 deg Down",
	"Right Banked Quarter Turn 3 Tile 25 deg Down",
	"Left Banked Quarter Turn 5 Tile 25 deg Up",
	"Right Banked Quarter Turn 5 Tile 25 deg Up",
	"Left Banked Quarter Turn 5 Tile 25 deg Down",
	"Right Banked Quarter Turn 5 Tile 25 deg Down",
	"25 Deg up to Left Banked 25 deg Up",
	"25 Deg up to Right Banked 25 deg Up",
	"Left Banked 25 deg up to 25 deg Up",
	"Right Banked 25 deg up to 25 deg Up",
	"25 Deg Down to Left Banked 25 deg Down",
	"25 Deg Down to Right Banked 25 deg Down",
	"Left Banked 25 deg Down to 25 deg Down",
	"Right Banked 25 deg Down to 25 deg Down",
	"Left Banked Flat to Left Banked 25 deg Up",
	"Right Banked Flat to Right Banked 25 deg Up",
	"Left Banked 25 deg up to Left Banked Flat",
	"Right Banked 25 deg up to Right Banked Flat",
	"Left Banked Flat to Left Banked 25 deg Down",
	"Right Banked Flat to Right Banked 25 deg Down",
	"Left Banked 25 deg Down to Left Banked Flat",
	"Right Banked 25 deg Down to Right Banked Flat",
	"Flat to Left Banked 25 deg Up",
	"Flat to Right Banked 25 deg Up",
	"Left Banked 25 deg up to Flat",
	"Right Banked 25 deg up to Flat",
	"Flat to Left Banked 25 deg Down",
	"Flat to Right Banked 25 deg Down",
	"Left Banked 25 deg Down to Flat",
	"Right Banked 25 deg Down to Flat",
	"Left Quarter Turn 1 Tile 90 deg Up",
	"Right Quarter Turn 1 Tile 90 deg Up",
	"Left Quarter Turn 1 Tile 90 deg Down",
	"Right Quarter Turn 1 Tile 90 deg Down",
	"Multidim 90 deg up to Inverted Flat Quarter Loop",
	"Multidim Flat to 90 deg Down Quarter Loop",
};

const utf8string FlatTrackNames[256] = {
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"FLAT_TRACK_ELEM_1_X_4_A = 95,",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"FLAT_TRACK_ELEM_2_X_2 = 110,",
	"FLAT_TRACK_ELEM_4_X_4 = 111,",
	"",
	"",
	"",
	"",
	"FLAT_TRACK_ELEM_1_X_5 = 116,",
	"",
	"FLAT_TRACK_ELEM_1_X_1_A = 118,",
	"FLAT_TRACK_ELEM_1_X_4_B = 119,",
	"",
	"FLAT_TRACK_ELEM_1_X_1_B = 121,",
	"FLAT_TRACK_ELEM_1_X_4_C = 122,",
	"FLAT_TRACK_ELEM_3_X_3 = 123,",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
};
