set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER gcc)
set(CMAKE_C_FLAGS_INIT -m32)
set(CMAKE_CXX_COMPILER g++)
set(CMAKE_CXX_FLAGS_INIT -m32)
set(CMAKE_EXE_LINKER_FLAGS_INIT -m32)
set(CMAKE_SHARED_LINKER_FLAGS_INIT -m32)

find_program(I386_EMULATOR NAMES i386)
set(CMAKE_CROSSCOMPILING_EMULATOR "${I386_EMULATOR}")