#!/usr/bin/env bash

set -e

echo -e "\033[0;36mBuilding AppImage for OpenRCT2...\033[0m"

# Ensure we are in root directory
basedir="$(readlink -f `dirname $0`/..)"
cd $basedir

linuxdeploy=/tmp/linuxdeploy-x86_64.AppImage
curl -fLo $linuxdeploy https://github.com/TheAssassin/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
chmod +x $linuxdeploy
pushd bin
    $linuxdeploy --appimage-extract-and-run --appdir install/ --output appimage --desktop-file install/usr/share/applications/openrct2.desktop
popd
mkdir -p artifacts
# If APPIMAGE_FILE_NAME is set, use it as the filename, otherwise use the default
if [ -z "$APPIMAGE_FILE_NAME" ]; then
    APPIMAGE_FILE_NAME=OpenRCT2-$OPENRCT2_VERSION-linux-x86_64.AppImage
fi
mv bin/OpenRCT2-x86_64.AppImage artifacts/$APPIMAGE_FILE_NAME
rm $linuxdeploy
