#!/usr/bin/env bash

set -e

echo -e "\033[0;36mBuilding AppImage for OpenRCT2...\033[0m"

# Ensure we are in root directory
basedir="$(readlink -f `dirname $0`/..)"
cd $basedir

linuxdeploy=/tmp/linuxdeploy-x86_64.AppImage
curl -fLo $linuxdeploy https://github.com/TheAssassin/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
chmod +x $linuxdeploy
pushd bin
    $linuxdeploy --appimage-extract-and-run --appdir install/ --output appimage --desktop-file install/usr/share/applications/openrct2.desktop
popd
mkdir -p artifacts
mv bin/OpenRCT2*.AppImage artifacts
rm $linuxdeploy
