#!/bin/bash
set -e

# Ensure we are in root directory
basedir="$(readlink -f `dirname $0`/..)"
cd $basedir

# Patch version.h
if [[ "$OPENRCT2_BUILD" != "" ]]; then
    echo -e "\033[0;36mPatching version.h...\033[0m"
    fileversion=$OPENRCT2_VERSION.$OPENRCT2_BUILD
    productversion="$fileversion-${OPENRCT2_SHA1_SHORT}"
    fileversion=${fileversion//./,}
    echo "#define OPENRCT2_FILE_VERSION $fileversion" > "resources/version.h"
    echo "#define OPENRCT2_PRODUCT_VERSION \"$productversion\"" >> "resources/version.h"
    cat "resources/version.h"
fi

# Build everything
echo -e "\033[0;36mBuilding OpenRCT2 for Windows $CONFIGURATION|$PLATFORM...\033[0m"
vstool msbuild openrct2.proj //t:build

# Create openrct2.exe and openrct2.com with correct subsystem
cp bin/openrct2.exe bin/openrct2.com
vstool editbin //subsystem:console bin/openrct2.com
vstool editbin //subsystem:windows bin/openrct2.exe
