#!/usr/bin/env bash

set -e

# Check 7z or zip is available
if [ -x "$(command -v 7z)" ]; then
    archiver="7z a"
elif [ -x "$(command -v zip)" ]; then
    archiver=zip
else
    echo -e >&2 "\033[0;7z and zip not found\033[0m"
    exit 1
fi

# Create a Windows symbols archive for OpenRCT2
basedir="$(readlink -f `dirname $0`/..)"
cd $basedir/bin

destination=../artifacts/openrct2-symbols-$CONFIGURATION-$PLATFORM.zip

echo -e "\033[0;36mCreating symbols archive for OpenRCT2...\033[0m"
if [[ -f $destination ]]; then
    rm $destination
fi
$archiver $destination openrct2.exe openrct2.com openrct2-win.pdb

destination=$(cygpath -w $(readlink -f $destination))
printf '\033[0;32m%s\033[0m\n' "${destination} created successfully"
