#!/bin/sh
set -e

# Ensure we are in root directory
basedir="$(readlink -f `dirname $0`/..)"
cd $basedir

git diff-index --quiet HEAD -- || echo 'Please commit changes before formatting' && exit 1

scripts/run-clang-format.py -r src test --exclude src/openrct2/thirdparty -i
