/*****************************************************************************
 * Copyright (c) 2014 Ted John
 * OpenRCT2, an open source clone of Roller Coaster Tycoon 2.
 *
 * This file is part of OpenRCT2.
 *
 * OpenRCT2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/

#ifndef _SPRITES_H_
#define _SPRITES_H_

enum {
	SPR_NONE = -1,

	SPR_RESIZE = 5058,

	SPR_HEARING_VIEWPORT = 5166,
	SPR_LOCATE = 5167,
	SPR_RENAME = 5168,

	SPR_BUY_LAND_RIGHTS = 5176,
	SPR_BUY_CONSTRUCTION_RIGHTS = 5177,
	SPR_NO_ENTRY = 5178,
	SPR_CLOSED = 5179,
	SPR_OPEN = 5180,
	SPR_TESTING = 5181,

	SPR_RIDE = 5187,
	SPR_TRACK_PEEP = 5188,
	SPR_SCENERY = 5189,
	SPR_FINANCE = 5190,
	SPR_NEW_RIDE = 5191,
	SPR_MAP = 5192,
	SPR_GUESTS = 5193,
	SPR_AWARD = 5194,
	SPR_GRAPH = 5195,

	SPR_LAND_TOOL_DECREASE = 5499,

	SPR_LAND_TOOL_INCREASE = 5501,

	SPR_LAND_TOOL_SIZE_0 = 5503,
	SPR_LAND_TOOL_SIZE_1 = SPR_LAND_TOOL_SIZE_0 + 1,
	SPR_LAND_TOOL_SIZE_2 = SPR_LAND_TOOL_SIZE_0 + 2,
	SPR_LAND_TOOL_SIZE_3 = SPR_LAND_TOOL_SIZE_0 + 3,
	SPR_LAND_TOOL_SIZE_4 = SPR_LAND_TOOL_SIZE_0 + 4,
	SPR_LAND_TOOL_SIZE_5 = SPR_LAND_TOOL_SIZE_0 + 5,
	SPR_LAND_TOOL_SIZE_6 = SPR_LAND_TOOL_SIZE_0 + 6,
	SPR_LAND_TOOL_SIZE_7 = SPR_LAND_TOOL_SIZE_0 + 7,

	SPR_TAB_OBJECTIVE_0 = 5511,
	SPR_TAB_OBJECTIVE_1 = SPR_TAB_OBJECTIVE_0 + 1,
	SPR_TAB_OBJECTIVE_2 = SPR_TAB_OBJECTIVE_0 + 2,
	SPR_TAB_OBJECTIVE_3 = SPR_TAB_OBJECTIVE_0 + 3,
	SPR_TAB_OBJECTIVE_4 = SPR_TAB_OBJECTIVE_0 + 4,
	SPR_TAB_OBJECTIVE_5 = SPR_TAB_OBJECTIVE_0 + 5,
	SPR_TAB_OBJECTIVE_6 = SPR_TAB_OBJECTIVE_0 + 6,
	SPR_TAB_OBJECTIVE_7 = SPR_TAB_OBJECTIVE_0 + 7,
	SPR_TAB_OBJECTIVE_8 = SPR_TAB_OBJECTIVE_0 + 8,
	SPR_TAB_OBJECTIVE_9 = SPR_TAB_OBJECTIVE_0 + 9,
	SPR_TAB_OBJECTIVE_10 = SPR_TAB_OBJECTIVE_0 + 10,
	SPR_TAB_OBJECTIVE_11 = SPR_TAB_OBJECTIVE_0 + 11,
	SPR_TAB_OBJECTIVE_12 = SPR_TAB_OBJECTIVE_0 + 12,
	SPR_TAB_OBJECTIVE_13 = SPR_TAB_OBJECTIVE_0 + 13,
	SPR_TAB_OBJECTIVE_14 = SPR_TAB_OBJECTIVE_0 + 14,
	SPR_TAB_OBJECTIVE_15 = SPR_TAB_OBJECTIVE_0 + 15,

	SPR_TOOLBAR_PAUSE = 5597,
	SPR_TOOLBAR_FILE = 5599,
	SPR_TOOLBAR_ZOOM_OUT = 5601,
	SPR_TOOLBAR_ZOOM_IN = 5604,
	SPR_TOOLBAR_ROTATE = 5607,
	SPR_TOOLBAR_LAND = 5609,
	SPR_TOOLBAR_MAP = 5611,
	SPR_TOOLBAR_GUESTS = 5613,
	SPR_TOOLBAR_SCENERY = 5615,
	SPR_TOOLBAR_WATER = 5617,
	SPR_TOOLBAR_RIDES = 5619,
	SPR_TOOLBAR_VIEW = 5621,
	SPR_TOOLBAR_FOOTPATH = 5623,
	SPR_TOOLBAR_STAFF = 5627,
	SPR_TOOLBAR_PARK = 5629,
	SPR_TOOLBAR_CONSTRUCT_RIDE = 5631,
	SPR_TOOLBAR_CLEAR_SCENERY = 5633,

	SPR_NEXT_WEATHER = 23189,
	SPR_WEATHER_SUN = 23190,
	SPR_WEATHER_SUN_CLOUD = 23191,
	SPR_WEATHER_CLOUD = 23192,
	SPR_WEATHER_LIGHT_RAIN = 23193,
	SPR_WEATHER_HEAVY_RAIN = 23194,
	SPR_WEATHER_STORM = 23195,
	SPR_WEATHER_UNKNOWN = 23196,

	SPR_RATING_LOW = 23197,
	SPR_RATING_HIGH = 23198,

	SPR_MENU_NEW_GAME = 23207,
	SPR_MENU_LOAD_GAME = 23208,
	SPR_MENU_TUTORIAL = 23209,
	SPR_MENU_EXIT = 23210,
	SPR_MENU_TOOLBOX = 23211,
	SPR_MENU_LOGO = 23212,
	SPR_CREDITS_LOGO_SMALL = 23213,
	SPR_CREDITS_CHRIS_SAWYER_SMALL = 23214,
	SPR_INTRO_CHRIS_SAWYER_00 = 23215,
	SPR_INTRO_CHRIS_SAWYER_10 = SPR_INTRO_CHRIS_SAWYER_00 + 1,
	SPR_INTRO_LOGO_00 = 23218,
	SPR_INTRO_LOGO_10 = SPR_INTRO_LOGO_00 + 1,
	SPR_INTRO_LOGO_20 = SPR_INTRO_LOGO_00 + 2,
	SPR_INTRO_LOGO_01 = SPR_INTRO_LOGO_00 + 3,
	SPR_INTRO_LOGO_11 = SPR_INTRO_LOGO_00 + 4,
	SPR_INTRO_LOGO_21 = SPR_INTRO_LOGO_00 + 5,

	SPR_SIX_FLAGS = 23225,
	SPR_INTRO_INFOGRAMES_00 = 23226,
	SPR_INTRO_INFOGRAMES_10 = SPR_INTRO_INFOGRAMES_00 + 1,
	SPR_INTRO_INFOGRAMES_01 = SPR_INTRO_INFOGRAMES_00 + 2,
	SPR_INTRO_INFOGRAMES_11 = SPR_INTRO_INFOGRAMES_00 + 3,
	SPR_CREDITS_INFOGRAMES = 23230,
};

#endif