/*****************************************************************************
 * Copyright (c) 2014 Ted John
 * OpenRCT2, an open source clone of Roller Coaster Tycoon 2.
 *
 * This file is part of OpenRCT2.
 *
 * OpenRCT2 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/

#include "addresses.h"
#include "track.h"

/**
 *
 *  rct2: 0x00997C9D
 */
const rct_trackdefinition gTrackDefinitions[] = {
    // TYPE			VANGLE END		VANGLE START	BANK END			BANK START			SPECIAL
    { TRACK_FLAT,	TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,	TRACK_BANK_NONE,	TRACK_NONE },		// flat
    { TRACK_FLAT,	TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,	TRACK_BANK_NONE,	TRACK_NONE },		// station end
    { TRACK_FLAT,	TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,	TRACK_BANK_NONE,	TRACK_NONE },		// station begin
    { TRACK_FLAT,	TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,	TRACK_BANK_NONE,	TRACK_NONE },		// station middle
    { TRACK_FLAT,	TRACK_UP_25,	TRACK_UP_25,	TRACK_BANK_NONE,	TRACK_BANK_NONE,	TRACK_NONE },		// 25 deg up
    { TRACK_FLAT,	TRACK_UP_60,	TRACK_UP_60,	TRACK_BANK_NONE,	TRACK_BANK_NONE,	TRACK_NONE },		// 60 deg up
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_25_DEG_UP
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_UP_TO_60_DEG_UP
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_UP_TO_25_DEG_UP
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_UP_TO_FLAT
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN_TO_60_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_DOWN_TO_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN_TO_FLAT
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_5_TILES
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_5_TILES
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_LEFT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_RIGHT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_BANK_TO_FLAT
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_BANK_TO_FLAT
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_BANKED_LEFT_QUARTER_TURN_5_TILES
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_BANKED_RIGHT_QUARTER_TURN_5_TILES
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_BANK_TO_25_DEG_UP
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_BANK_TO_25_DEG_UP
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_LEFT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_UP_TO_LEFT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_RIGHT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_UP_TO_RIGHT_BANK
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_BANK_TO_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_BANK_TO_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_25,		TRACK_BANK_LEFT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN_TO_LEFT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_25,		TRACK_BANK_RIGHT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN_TO_RIGHT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_BANK
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_5_TILES_25_DEG_UP
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_5_TILES_25_DEG_UP
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_5_TILES_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_5_TILES_25_DEG_DOWN
    { TRACK_S_BEND,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_S_BEND_LEFT
    { TRACK_S_BEND,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_S_BEND_RIGHT
    { TRACK_VERTICAL_LOOP,		TRACK_DOWN_25,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_UNKNOWN_VERTICAL_LOOP,		 },		// ELEM_LEFT_VERTICAL_LOOP
    { TRACK_VERTICAL_LOOP,		TRACK_DOWN_25,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_UNKNOWN_VERTICAL_LOOP,		 },		// ELEM_RIGHT_VERTICAL_LOOP
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_3_TILES
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_3_TILES
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_3_TILES_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_3_TILES_BANK
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_3_TILES_25_DEG_UP
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_3_TILES_25_DEG_UP
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_3_TILES_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_3_TILES_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_1_TILE
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_1_TILE
    { TRACK_TWIST,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_TWIST_DOWN_TO_UP
    { TRACK_TWIST,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_TWIST_DOWN_TO_UP
    { TRACK_TWIST,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_NONE,		 },		// ELEM_LEFT_TWIST_UP_TO_DOWN
    { TRACK_TWIST,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_NONE,		 },		// ELEM_RIGHT_TWIST_UP_TO_DOWN
    { TRACK_HALF_LOOP,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_UPSIDE_DOWN,		TRACK_BANK_NONE,		TRACK_HALF_LOOP_UP,		 },		// ELEM_HALF_LOOP_UP
    { TRACK_HALF_LOOP,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_HALF_LOOP_DOWN,		 },		// ELEM_HALF_LOOP_DOWN
    { TRACK_CORKSCREW,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_CORKSCREW_UP
    { TRACK_CORKSCREW,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_CORKSCREW_UP
    { TRACK_CORKSCREW,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_CORKSCREW_DOWN,		 },		// ELEM_LEFT_CORKSCREW_DOWN
    { TRACK_CORKSCREW,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_CORKSCREW_DOWN,		 },		// ELEM_RIGHT_CORKSCREW_DOWN
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_60_DEG_UP
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_UP_TO_FLAT
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_60_DEG_DOWN
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_DOWN_TO_FLAT
    { TRACK_TOWER_BASE,		TRACK_UP_90,		TRACK_UP_90,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_TOWER_BASE
    { TRACK_TOWER_BASE,		TRACK_UP_90,		TRACK_UP_90,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_TOWER_SECTION
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_COVERED
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_UP_COVERED
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_UP_COVERED
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_25_DEG_UP_COVERED
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_UP_TO_60_DEG_UP_COVERED
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_UP_TO_25_DEG_UP_COVERED
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_UP_TO_FLAT_COVERED
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN_COVERED
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_DOWN_COVERED
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_25_DEG_DOWN_COVERED
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN_TO_60_DEG_DOWN_COVERED
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_DOWN_TO_25_DEG_DOWN_COVERED
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN_TO_FLAT_COVERED
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_5_TILES_COVERED
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_5_TILES_COVERED
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_S_BEND_LEFT_COVERED
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_S_BEND_RIGHT_COVERED
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_3_TILES_COVERED
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_3_TILES_COVERED
    { TRACK_HELIX_SMALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_HALF_BANKED_HELIX_UP_SMALL
    { TRACK_HELIX_SMALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_HALF_BANKED_HELIX_UP_SMALL
    { TRACK_HELIX_SMALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_HALF_BANKED_HELIX_DOWN_SMALL
    { TRACK_HELIX_SMALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_HALF_BANKED_HELIX_DOWN_SMALL
    { TRACK_HELIX_SMALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_HALF_BANKED_HELIX_UP_LARGE
    { TRACK_HELIX_SMALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_HALF_BANKED_HELIX_UP_LARGE
    { TRACK_HELIX_SMALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_HALF_BANKED_HELIX_DOWN_LARGE
    { TRACK_HELIX_SMALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_HALF_BANKED_HELIX_DOWN_LARGE
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_1_TILE_60_DEG_UP
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_1_TILE_60_DEG_UP
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_1_TILE_60_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_1_TILE_60_DEG_DOWN
    { TRACK_BRAKES,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_BRAKES
    { TRACK_ROTATION_CONTROL_TOGGLE,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_ROTATION_CONTROL_TOGGLE
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_INVERTED_90_DEG_UP_TO_FLAT_QUARTER_LOOP
    { TRACK_HELIX_LARGE,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_BANKED_HELIX_LARGE_UP
    { TRACK_HELIX_LARGE,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_BANKED_HELIX_LARGE_UP
    { TRACK_HELIX_LARGE,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_BANKED_HELIX_LARGE_DOWN
    { TRACK_HELIX_LARGE,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_BANKED_HELIX_LARGE_DOWN
    { TRACK_HELIX_LARGE_UNBANKED,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_HELIX_LARGE_UP
    { TRACK_HELIX_LARGE_UNBANKED,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_HELIX_LARGE_UP
    { TRACK_HELIX_LARGE_UNBANKED,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_HELIX_LARGE_DOWN
    { TRACK_HELIX_LARGE_UNBANKED,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_HELIX_LARGE_DOWN
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_25,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_25_DEG_UP_LEFT_BANKED
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_25,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_25_DEG_UP_RIGHT_BANKED
    { TRACK_WATERFALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_WATERFALL
    { TRACK_RAPIDS,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RAPIDS
    { TRACK_ON_RIDE_PHOTO,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_ON_RIDE_PHOTO
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_25,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN_LEFT_BANKED
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_25,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_25_DEG_DOWN_RIGHT_BANKED
    { TRACK_WATER_SPLASH,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_WATER_SPLASH
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_60_DEG_UP_LONG_BASE
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_UP_TO_FLAT_LONG_BASE
    { TRACK_WATERFALL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_WHIRLPOOL
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_FLAT_TO_60_DEG_DOWN_LONG_BASE
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_UP_TO_FLAT_LONG_BASE
    { TRACK_LIFT_HILL,		TRACK_DOWN_60,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_CABLE_LIFT_HILL
    { TRACK_WHOA_BELLY,		TRACK_UP_90,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_REVERSE_WHOA_BELLY_SLOPE
    { TRACK_WHOA_BELLY,		TRACK_UP_90,		TRACK_UP_90,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_REVERSE_WHOA_BELLY_VERTICAL
    { TRACK_FLAT,		TRACK_UP_90,		TRACK_UP_90,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_90_DEG_UP
    { TRACK_FLAT,		TRACK_DOWN_90,		TRACK_DOWN_90,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_90_DEG_DOWN
    { TRACK_FLAT,		TRACK_UP_90,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_UP_TO_90_DEG_UP
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_DOWN_90,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_90_DEG_DOWN_TO_60_DEG_DOWN
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_UP_90,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_90_DEG_UP_TO_60_DEG_UP
    { TRACK_FLAT,		TRACK_DOWN_90,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_60_DEG_DOWN_TO_90_DEG_DOWN
    { TRACK_BRAKE_FOR_DROP,		TRACK_DOWN_60,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_BRAKE_FOR_DROP
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_EIGHTH_TO_DIAG
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_EIGHTH_TO_DIAG
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_EIGHTH_TO_ORTHOGONAL
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_EIGHTH_TO_ORTHOGONAL
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_EIGHTH_BANK_TO_DIAG
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_EIGHTH_BANK_TO_DIAG
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_EIGHTH_BANK_TO_ORTHOGONAL
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_EIGHTH_BANK_TO_ORTHOGONAL
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_FLAT
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_UP
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_60_DEG_UP
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_FLAT_TO_25_DEG_UP
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_UP_TO_60_DEG_UP
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_60_DEG_UP_TO_25_DEG_UP
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_UP_TO_FLAT
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_60_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_FLAT_TO_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_DOWN_TO_60_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_60_DEG_DOWN_TO_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_DOWN_TO_FLAT
    { TRACK_FLAT,		TRACK_UP_60,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_FLAT_TO_60_DEG_UP
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_60_DEG_UP_TO_FLAT
    { TRACK_FLAT,		TRACK_DOWN_60,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_FLAT_TO_60_DEG_DOWN
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_60,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_60_DEG_DOWN_TO_FLAT
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_FLAT_TO_LEFT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_FLAT_TO_RIGHT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_DIAG_LEFT_BANK_TO_FLAT
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_DIAG_RIGHT_BANK_TO_FLAT
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_DIAG_LEFT_BANK_TO_25_DEG_UP
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_DIAG_RIGHT_BANK_TO_25_DEG_UP
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_LEFT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_UP_TO_LEFT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_RIGHT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_UP_TO_RIGHT_BANK
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_DIAG_LEFT_BANK_TO_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_DIAG_RIGHT_BANK_TO_25_DEG_DOWN
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_25,		TRACK_BANK_LEFT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_DOWN_TO_LEFT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_25,		TRACK_BANK_RIGHT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_DIAG_25_DEG_DOWN_TO_RIGHT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_LEFT,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_DIAG_LEFT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_RIGHT,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_DIAG_RIGHT_BANK
    { TRACK_LOG_FLUME_REVERSER,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LOG_FLUME_REVERSER
    { TRACK_SPINNING_TUNNEL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_SPINNING_TUNNEL
    { TRACK_BARREL_ROLL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_BARREL_ROLL_UP_TO_DOWN
    { TRACK_BARREL_ROLL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_BARREL_ROLL_UP_TO_DOWN
    { TRACK_BARREL_ROLL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_NONE,		 },		// ELEM_LEFT_BARREL_ROLL_DOWN_TO_UP
    { TRACK_BARREL_ROLL,		TRACK_NONE,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_NONE,		 },		// ELEM_RIGHT_BARREL_ROLL_DOWN_TO_UP
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_LEFT,		TRACK_NONE,		 },		// ELEM_LEFT_BANK_TO_LEFT_QUARTER_TURN_3_TILES_25_DEG_UP
    { TRACK_FLAT,		TRACK_UP_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_RIGHT,		TRACK_NONE,		 },		// ELEM_RIGHT_BANK_TO_RIGHT_QUARTER_TURN_3_TILES_25_DEG_UP
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_25,		TRACK_BANK_LEFT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_LEFT_QUARTER_TURN_3_TILES_25_DEG_DOWN_TO_LEFT_BANK
    { TRACK_FLAT,		TRACK_NONE,		TRACK_DOWN_25,		TRACK_BANK_RIGHT,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_RIGHT_QUARTER_TURN_3_TILES_25_DEG_DOWN_TO_RIGHT_BANK
    { TRACK_POWERED_LIFT,		TRACK_UP_25,		TRACK_UP_25,		TRACK_BANK_NONE,		TRACK_BANK_NONE,		TRACK_NONE,		 },		// ELEM_POWERED_LIFT
    { TRACK_HALF_LOOP_2,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_UPSIDE_DOWN,		TRACK_BANK_NONE,		TRACK_HALF_LOOP_UP,		 },		// ELEM_LEFT_LARGE_HALF_LOOP_UP
    { TRACK_HALF_LOOP_2,		TRACK_NONE,		TRACK_UP_25,		TRACK_BANK_UPSIDE_DOWN,		TRACK_BANK_NONE,		TRACK_HALF_LOOP_UP,		 },		// ELEM_RIGHT_LARGE_HALF_LOOP_UP
    { TRACK_HALF_LOOP_2,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_HALF_LOOP_DOWN,		 },		// ELEM_RIGHT_LARGE_HALF_LOOP_DOWN
    { TRACK_HALF_LOOP_2,		TRACK_DOWN_25,		TRACK_NONE,		TRACK_BANK_NONE,		TRACK_BANK_UPSIDE_DOWN,		TRACK_HALF_LOOP_DOWN,		 },		// ELEM_LEFT_LARGE_HALF_LOOP_DOWN
};

/**
 *
 *  rct2: 0x006CED50
 */
void track_load_list(int edx)
{
    RCT2_CALLPROC_X(0x006CED50, 0, 0, 0, edx, 0, 0, 0);
}
