/*****************************************************************************
 * Copyright (c) 2014-2021 OpenRCT2 developers
 *
 * For a complete list of all authors, please refer to contributors.md
 * Interested in contributing? Visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is licensed under the GNU General Public License version 3.
 *****************************************************************************/
#pragma once

namespace OpenRCT2::Profiling
{
    // TODO: This is an abomination, refactor this once C++20 is used.
#define PROFILING_CHAR_FROM_INDEX(name, i) (i >= (sizeof(name) / sizeof(*name)) ? 0 : name[i])
#define PROFILING_CHAR_BUILDER(name)                                                                                           \
    PROFILING_CHAR_FROM_INDEX(name, 0)                                                                                         \
    , PROFILING_CHAR_FROM_INDEX(name, 1), PROFILING_CHAR_FROM_INDEX(name, 2), PROFILING_CHAR_FROM_INDEX(name, 3),              \
        PROFILING_CHAR_FROM_INDEX(name, 4), PROFILING_CHAR_FROM_INDEX(name, 5), PROFILING_CHAR_FROM_INDEX(name, 6),            \
        PROFILING_CHAR_FROM_INDEX(name, 7), PROFILING_CHAR_FROM_INDEX(name, 8), PROFILING_CHAR_FROM_INDEX(name, 9),            \
        PROFILING_CHAR_FROM_INDEX(name, 10), PROFILING_CHAR_FROM_INDEX(name, 11), PROFILING_CHAR_FROM_INDEX(name, 12),         \
        PROFILING_CHAR_FROM_INDEX(name, 13), PROFILING_CHAR_FROM_INDEX(name, 14), PROFILING_CHAR_FROM_INDEX(name, 15),         \
        PROFILING_CHAR_FROM_INDEX(name, 16), PROFILING_CHAR_FROM_INDEX(name, 17), PROFILING_CHAR_FROM_INDEX(name, 18),         \
        PROFILING_CHAR_FROM_INDEX(name, 19), PROFILING_CHAR_FROM_INDEX(name, 20), PROFILING_CHAR_FROM_INDEX(name, 21),         \
        PROFILING_CHAR_FROM_INDEX(name, 22), PROFILING_CHAR_FROM_INDEX(name, 23), PROFILING_CHAR_FROM_INDEX(name, 24),         \
        PROFILING_CHAR_FROM_INDEX(name, 25), PROFILING_CHAR_FROM_INDEX(name, 26), PROFILING_CHAR_FROM_INDEX(name, 27),         \
        PROFILING_CHAR_FROM_INDEX(name, 28), PROFILING_CHAR_FROM_INDEX(name, 29), PROFILING_CHAR_FROM_INDEX(name, 30),         \
        PROFILING_CHAR_FROM_INDEX(name, 31), PROFILING_CHAR_FROM_INDEX(name, 32), PROFILING_CHAR_FROM_INDEX(name, 33),         \
        PROFILING_CHAR_FROM_INDEX(name, 34), PROFILING_CHAR_FROM_INDEX(name, 35), PROFILING_CHAR_FROM_INDEX(name, 36),         \
        PROFILING_CHAR_FROM_INDEX(name, 37), PROFILING_CHAR_FROM_INDEX(name, 38), PROFILING_CHAR_FROM_INDEX(name, 39),         \
        PROFILING_CHAR_FROM_INDEX(name, 40), PROFILING_CHAR_FROM_INDEX(name, 41), PROFILING_CHAR_FROM_INDEX(name, 42),         \
        PROFILING_CHAR_FROM_INDEX(name, 43), PROFILING_CHAR_FROM_INDEX(name, 44), PROFILING_CHAR_FROM_INDEX(name, 45),         \
        PROFILING_CHAR_FROM_INDEX(name, 46), PROFILING_CHAR_FROM_INDEX(name, 47), PROFILING_CHAR_FROM_INDEX(name, 48),         \
        PROFILING_CHAR_FROM_INDEX(name, 49), PROFILING_CHAR_FROM_INDEX(name, 50), PROFILING_CHAR_FROM_INDEX(name, 51),         \
        PROFILING_CHAR_FROM_INDEX(name, 52), PROFILING_CHAR_FROM_INDEX(name, 53), PROFILING_CHAR_FROM_INDEX(name, 54),         \
        PROFILING_CHAR_FROM_INDEX(name, 55), PROFILING_CHAR_FROM_INDEX(name, 56), PROFILING_CHAR_FROM_INDEX(name, 57),         \
        PROFILING_CHAR_FROM_INDEX(name, 58), PROFILING_CHAR_FROM_INDEX(name, 59), PROFILING_CHAR_FROM_INDEX(name, 60),         \
        PROFILING_CHAR_FROM_INDEX(name, 61), PROFILING_CHAR_FROM_INDEX(name, 62), PROFILING_CHAR_FROM_INDEX(name, 63),         \
        PROFILING_CHAR_FROM_INDEX(name, 64), PROFILING_CHAR_FROM_INDEX(name, 65), PROFILING_CHAR_FROM_INDEX(name, 66),         \
        PROFILING_CHAR_FROM_INDEX(name, 67), PROFILING_CHAR_FROM_INDEX(name, 68), PROFILING_CHAR_FROM_INDEX(name, 69),         \
        PROFILING_CHAR_FROM_INDEX(name, 70), PROFILING_CHAR_FROM_INDEX(name, 71), PROFILING_CHAR_FROM_INDEX(name, 72),         \
        PROFILING_CHAR_FROM_INDEX(name, 73), PROFILING_CHAR_FROM_INDEX(name, 74), PROFILING_CHAR_FROM_INDEX(name, 75),         \
        PROFILING_CHAR_FROM_INDEX(name, 76), PROFILING_CHAR_FROM_INDEX(name, 77), PROFILING_CHAR_FROM_INDEX(name, 78),         \
        PROFILING_CHAR_FROM_INDEX(name, 79), PROFILING_CHAR_FROM_INDEX(name, 80), PROFILING_CHAR_FROM_INDEX(name, 81),         \
        PROFILING_CHAR_FROM_INDEX(name, 82), PROFILING_CHAR_FROM_INDEX(name, 83), PROFILING_CHAR_FROM_INDEX(name, 84),         \
        PROFILING_CHAR_FROM_INDEX(name, 85), PROFILING_CHAR_FROM_INDEX(name, 86), PROFILING_CHAR_FROM_INDEX(name, 87),         \
        PROFILING_CHAR_FROM_INDEX(name, 88), PROFILING_CHAR_FROM_INDEX(name, 89), PROFILING_CHAR_FROM_INDEX(name, 90),         \
        PROFILING_CHAR_FROM_INDEX(name, 91), PROFILING_CHAR_FROM_INDEX(name, 92), PROFILING_CHAR_FROM_INDEX(name, 93),         \
        PROFILING_CHAR_FROM_INDEX(name, 94), PROFILING_CHAR_FROM_INDEX(name, 95), PROFILING_CHAR_FROM_INDEX(name, 96),         \
        PROFILING_CHAR_FROM_INDEX(name, 97), PROFILING_CHAR_FROM_INDEX(name, 98), PROFILING_CHAR_FROM_INDEX(name, 99),         \
        PROFILING_CHAR_FROM_INDEX(name, 100), PROFILING_CHAR_FROM_INDEX(name, 101), PROFILING_CHAR_FROM_INDEX(name, 102),      \
        PROFILING_CHAR_FROM_INDEX(name, 103), PROFILING_CHAR_FROM_INDEX(name, 104), PROFILING_CHAR_FROM_INDEX(name, 105),      \
        PROFILING_CHAR_FROM_INDEX(name, 106), PROFILING_CHAR_FROM_INDEX(name, 107), PROFILING_CHAR_FROM_INDEX(name, 108),      \
        PROFILING_CHAR_FROM_INDEX(name, 109), PROFILING_CHAR_FROM_INDEX(name, 110), PROFILING_CHAR_FROM_INDEX(name, 111),      \
        PROFILING_CHAR_FROM_INDEX(name, 112), PROFILING_CHAR_FROM_INDEX(name, 113), PROFILING_CHAR_FROM_INDEX(name, 114),      \
        PROFILING_CHAR_FROM_INDEX(name, 115), PROFILING_CHAR_FROM_INDEX(name, 116), PROFILING_CHAR_FROM_INDEX(name, 117),      \
        PROFILING_CHAR_FROM_INDEX(name, 118), PROFILING_CHAR_FROM_INDEX(name, 119), PROFILING_CHAR_FROM_INDEX(name, 120),      \
        PROFILING_CHAR_FROM_INDEX(name, 121), PROFILING_CHAR_FROM_INDEX(name, 122), PROFILING_CHAR_FROM_INDEX(name, 123),      \
        PROFILING_CHAR_FROM_INDEX(name, 124), PROFILING_CHAR_FROM_INDEX(name, 125), PROFILING_CHAR_FROM_INDEX(name, 126),      \
        PROFILING_CHAR_FROM_INDEX(name, 127), PROFILING_CHAR_FROM_INDEX(name, 128), PROFILING_CHAR_FROM_INDEX(name, 129),      \
        PROFILING_CHAR_FROM_INDEX(name, 130), PROFILING_CHAR_FROM_INDEX(name, 131), PROFILING_CHAR_FROM_INDEX(name, 132),      \
        PROFILING_CHAR_FROM_INDEX(name, 133), PROFILING_CHAR_FROM_INDEX(name, 134), PROFILING_CHAR_FROM_INDEX(name, 135),      \
        PROFILING_CHAR_FROM_INDEX(name, 136), PROFILING_CHAR_FROM_INDEX(name, 137), PROFILING_CHAR_FROM_INDEX(name, 138),      \
        PROFILING_CHAR_FROM_INDEX(name, 139), PROFILING_CHAR_FROM_INDEX(name, 140), PROFILING_CHAR_FROM_INDEX(name, 141),      \
        PROFILING_CHAR_FROM_INDEX(name, 142), PROFILING_CHAR_FROM_INDEX(name, 143), PROFILING_CHAR_FROM_INDEX(name, 144),      \
        PROFILING_CHAR_FROM_INDEX(name, 145), PROFILING_CHAR_FROM_INDEX(name, 146), PROFILING_CHAR_FROM_INDEX(name, 147),      \
        PROFILING_CHAR_FROM_INDEX(name, 148), PROFILING_CHAR_FROM_INDEX(name, 149), PROFILING_CHAR_FROM_INDEX(name, 150),      \
        PROFILING_CHAR_FROM_INDEX(name, 151), PROFILING_CHAR_FROM_INDEX(name, 152), PROFILING_CHAR_FROM_INDEX(name, 153),      \
        PROFILING_CHAR_FROM_INDEX(name, 154), PROFILING_CHAR_FROM_INDEX(name, 155), PROFILING_CHAR_FROM_INDEX(name, 156),      \
        PROFILING_CHAR_FROM_INDEX(name, 157), PROFILING_CHAR_FROM_INDEX(name, 158), PROFILING_CHAR_FROM_INDEX(name, 159),      \
        PROFILING_CHAR_FROM_INDEX(name, 160), PROFILING_CHAR_FROM_INDEX(name, 161), PROFILING_CHAR_FROM_INDEX(name, 162),      \
        PROFILING_CHAR_FROM_INDEX(name, 163), PROFILING_CHAR_FROM_INDEX(name, 164), PROFILING_CHAR_FROM_INDEX(name, 165),      \
        PROFILING_CHAR_FROM_INDEX(name, 166), PROFILING_CHAR_FROM_INDEX(name, 167), PROFILING_CHAR_FROM_INDEX(name, 168),      \
        PROFILING_CHAR_FROM_INDEX(name, 169), PROFILING_CHAR_FROM_INDEX(name, 170), PROFILING_CHAR_FROM_INDEX(name, 171),      \
        PROFILING_CHAR_FROM_INDEX(name, 172), PROFILING_CHAR_FROM_INDEX(name, 173), PROFILING_CHAR_FROM_INDEX(name, 174),      \
        PROFILING_CHAR_FROM_INDEX(name, 175), PROFILING_CHAR_FROM_INDEX(name, 176), PROFILING_CHAR_FROM_INDEX(name, 177),      \
        PROFILING_CHAR_FROM_INDEX(name, 178), PROFILING_CHAR_FROM_INDEX(name, 179), PROFILING_CHAR_FROM_INDEX(name, 180),      \
        PROFILING_CHAR_FROM_INDEX(name, 181), PROFILING_CHAR_FROM_INDEX(name, 182), PROFILING_CHAR_FROM_INDEX(name, 183),      \
        PROFILING_CHAR_FROM_INDEX(name, 184), PROFILING_CHAR_FROM_INDEX(name, 185), PROFILING_CHAR_FROM_INDEX(name, 186),      \
        PROFILING_CHAR_FROM_INDEX(name, 187), PROFILING_CHAR_FROM_INDEX(name, 188), PROFILING_CHAR_FROM_INDEX(name, 189),      \
        PROFILING_CHAR_FROM_INDEX(name, 190), PROFILING_CHAR_FROM_INDEX(name, 191), PROFILING_CHAR_FROM_INDEX(name, 192),      \
        PROFILING_CHAR_FROM_INDEX(name, 193), PROFILING_CHAR_FROM_INDEX(name, 194), PROFILING_CHAR_FROM_INDEX(name, 195),      \
        PROFILING_CHAR_FROM_INDEX(name, 196), PROFILING_CHAR_FROM_INDEX(name, 197), PROFILING_CHAR_FROM_INDEX(name, 198),      \
        PROFILING_CHAR_FROM_INDEX(name, 199), PROFILING_CHAR_FROM_INDEX(name, 200), PROFILING_CHAR_FROM_INDEX(name, 201),      \
        PROFILING_CHAR_FROM_INDEX(name, 202), PROFILING_CHAR_FROM_INDEX(name, 203), PROFILING_CHAR_FROM_INDEX(name, 204),      \
        PROFILING_CHAR_FROM_INDEX(name, 205), PROFILING_CHAR_FROM_INDEX(name, 206), PROFILING_CHAR_FROM_INDEX(name, 207),      \
        PROFILING_CHAR_FROM_INDEX(name, 208), PROFILING_CHAR_FROM_INDEX(name, 209), PROFILING_CHAR_FROM_INDEX(name, 210),      \
        PROFILING_CHAR_FROM_INDEX(name, 211), PROFILING_CHAR_FROM_INDEX(name, 212), PROFILING_CHAR_FROM_INDEX(name, 213),      \
        PROFILING_CHAR_FROM_INDEX(name, 214), PROFILING_CHAR_FROM_INDEX(name, 215), PROFILING_CHAR_FROM_INDEX(name, 216),      \
        PROFILING_CHAR_FROM_INDEX(name, 217), PROFILING_CHAR_FROM_INDEX(name, 218), PROFILING_CHAR_FROM_INDEX(name, 219),      \
        PROFILING_CHAR_FROM_INDEX(name, 220), PROFILING_CHAR_FROM_INDEX(name, 221), PROFILING_CHAR_FROM_INDEX(name, 222),      \
        PROFILING_CHAR_FROM_INDEX(name, 223), PROFILING_CHAR_FROM_INDEX(name, 224), PROFILING_CHAR_FROM_INDEX(name, 225),      \
        PROFILING_CHAR_FROM_INDEX(name, 226), PROFILING_CHAR_FROM_INDEX(name, 227), PROFILING_CHAR_FROM_INDEX(name, 228),      \
        PROFILING_CHAR_FROM_INDEX(name, 229), PROFILING_CHAR_FROM_INDEX(name, 230), PROFILING_CHAR_FROM_INDEX(name, 231),      \
        PROFILING_CHAR_FROM_INDEX(name, 232), PROFILING_CHAR_FROM_INDEX(name, 233), PROFILING_CHAR_FROM_INDEX(name, 234),      \
        PROFILING_CHAR_FROM_INDEX(name, 235), PROFILING_CHAR_FROM_INDEX(name, 236), PROFILING_CHAR_FROM_INDEX(name, 237),      \
        PROFILING_CHAR_FROM_INDEX(name, 238), PROFILING_CHAR_FROM_INDEX(name, 239), PROFILING_CHAR_FROM_INDEX(name, 240),      \
        PROFILING_CHAR_FROM_INDEX(name, 241), PROFILING_CHAR_FROM_INDEX(name, 242), PROFILING_CHAR_FROM_INDEX(name, 243),      \
        PROFILING_CHAR_FROM_INDEX(name, 244), PROFILING_CHAR_FROM_INDEX(name, 245), PROFILING_CHAR_FROM_INDEX(name, 246),      \
        PROFILING_CHAR_FROM_INDEX(name, 247), PROFILING_CHAR_FROM_INDEX(name, 248), PROFILING_CHAR_FROM_INDEX(name, 249),      \
        PROFILING_CHAR_FROM_INDEX(name, 250), PROFILING_CHAR_FROM_INDEX(name, 251), PROFILING_CHAR_FROM_INDEX(name, 252),      \
        PROFILING_CHAR_FROM_INDEX(name, 253), PROFILING_CHAR_FROM_INDEX(name, 254), '\0'

#if defined(__clang__) || defined(__GNUC__)
#    define PROFILING_FUNC_NAME __PRETTY_FUNCTION__
#elif defined(_MSC_VER)
#    define PROFILING_FUNC_NAME __FUNCSIG__
#else
#    error "Unsupported compiler"
#endif

#define PROFILED_FUNCTION()                                                                                                    \
    static_assert(                                                                                                             \
        sizeof(PROFILING_FUNC_NAME) / sizeof(*PROFILING_FUNC_NAME) < ::OpenRCT2::Profiling::Detail::MaxNameSize,               \
        "Function name is too big");                                                                                           \
    static auto& _profiling_func = ::OpenRCT2::Profiling::Detail::Storage<PROFILING_CHAR_BUILDER(PROFILING_FUNC_NAME)>::Data;  \
    ::OpenRCT2::Profiling::ScopedProfiling _profiling_scope(_profiling_func);

} // namespace OpenRCT2::Profiling
