/*****************************************************************************
 * Copyright (c) 2014-2026 OpenRCT2 developers
 *
 * For a complete list of all authors, please refer to contributors.md
 * Interested in contributing? Visit https://github.com/OpenRCT2/OpenRCT2
 *
 * OpenRCT2 is licensed under the GNU General Public License version 3.
 *****************************************************************************/

#pragma once

#include <cstdint>

namespace OpenRCT2
{
    enum class GameCommand : int32_t
    {
        setRideAppearance,
        setLandHeight,
        togglePause,
        placeTrack,
        removeTrack,
        loadOrQuit,
        createRide,
        demolishRide,
        setRideStatus,
        setRideVehicles,
        setRideName,
        setRideSetting,
        placeRideEntranceOrExit,
        removeRideEntranceOrExit,
        removeScenery,
        placeScenery,
        setWaterHeight,
        placePath,
        placePathLayout,
        removePath,
        changeSurfaceStyle,
        setRidePrice,
        setGuestName,
        setStaffName,
        raiseLand,
        lowerLand,
        editLandSmooth,
        raiseWater,
        lowerWater,
        setBrakesSpeed,
        hireNewStaffMember,
        setStaffPatrol,
        fireStaffMember,
        setStaffOrders,
        setParkName,
        setParkOpen,
        buyLandRights,
        placeParkEntrance,
        removeParkEntrance,
        setMazeTrack,
        setParkEntranceFee,
        setStaffColour,
        placeWall,
        removeWall,
        placeLargeScenery,
        removeLargeScenery,
        setCurrentLoan,
        setResearchFunding,
        placeTrackDesign,
        startMarketingCampaign,
        placeMazeDesign,
        placeBanner,
        removeBanner,
        setSceneryColour,
        setWallColour,
        setLargeSceneryColour,
        setBannerColour,
        setLandOwnership,
        clearScenery,
        setBannerName,
        setSignName,
        setBannerStyle,
        setSignStyle,
        setPlayerGroup,
        modifyGroups,
        kickPlayer,
        cheat,
        pickupGuest,
        pickupStaff,
        balloonPress,
        modifyTile,
        editScenarioOptions,
        placePeepSpawn,
        setColourScheme,
        setStaffCostume,
        placeFootpathAddition,
        removeFootpathAddition,
        guestSetFlags,
        setDate,
        custom,
        changeMapSize,
        freezeRideRating,
        setGameSpeed,
        setRestrictedScenery,
        setRideVisibility,
        setRideBreakdown,
        count,
    };
}
